/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Login implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String basketplanUsername;
    private String firstname;
    private String lastname;
    private String email;

    public Login() {}

    public Login(Login value) {
        this.id = value.id;
        this.basketplanUsername = value.basketplanUsername;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.email = value.email;
    }

    public Login(
        Long id,
        String basketplanUsername,
        String firstname,
        String lastname,
        String email
    ) {
        this.id = id;
        this.basketplanUsername = basketplanUsername;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
    }

    /**
     * Getter for <code>public.login.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.login.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.login.basketplan_username</code>.
     */
    public String getBasketplanUsername() {
        return this.basketplanUsername;
    }

    /**
     * Setter for <code>public.login.basketplan_username</code>.
     */
    public void setBasketplanUsername(String basketplanUsername) {
        this.basketplanUsername = basketplanUsername;
    }

    /**
     * Getter for <code>public.login.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.login.firstname</code>.
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Getter for <code>public.login.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.login.lastname</code>.
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Getter for <code>public.login.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.login.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Login other = (Login) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.basketplanUsername == null) {
            if (other.basketplanUsername != null)
                return false;
        }
        else if (!this.basketplanUsername.equals(other.basketplanUsername))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.basketplanUsername == null) ? 0 : this.basketplanUsername.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Login (");

        sb.append(id);
        sb.append(", ").append(basketplanUsername);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(email);

        sb.append(")");
        return sb.toString();
    }
}
