/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Login implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String firstname;
    private String lastname;
    private String email;
    private LocalDateTime lastLogin;
    private Boolean refereeCoach;
    private Boolean referee;
    private Boolean trainerCoach;
    private Boolean trainer;
    private Boolean admin;
    private String rank;
    private Boolean active;
    private Boolean refereeCoachPlus;
    private String username;

    public Login() {}

    public Login(Login value) {
        this.id = value.id;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.email = value.email;
        this.lastLogin = value.lastLogin;
        this.refereeCoach = value.refereeCoach;
        this.referee = value.referee;
        this.trainerCoach = value.trainerCoach;
        this.trainer = value.trainer;
        this.admin = value.admin;
        this.rank = value.rank;
        this.active = value.active;
        this.refereeCoachPlus = value.refereeCoachPlus;
        this.username = value.username;
    }

    public Login(
        Long id,
        String firstname,
        String lastname,
        String email,
        LocalDateTime lastLogin,
        Boolean refereeCoach,
        Boolean referee,
        Boolean trainerCoach,
        Boolean trainer,
        Boolean admin,
        String rank,
        Boolean active,
        Boolean refereeCoachPlus,
        String username
    ) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.lastLogin = lastLogin;
        this.refereeCoach = refereeCoach;
        this.referee = referee;
        this.trainerCoach = trainerCoach;
        this.trainer = trainer;
        this.admin = admin;
        this.rank = rank;
        this.active = active;
        this.refereeCoachPlus = refereeCoachPlus;
        this.username = username;
    }

    /**
     * Getter for <code>public.login.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.login.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.login.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.login.firstname</code>.
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Getter for <code>public.login.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.login.lastname</code>.
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Getter for <code>public.login.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.login.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.login.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return this.lastLogin;
    }

    /**
     * Setter for <code>public.login.last_login</code>.
     */
    public void setLastLogin(LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * Getter for <code>public.login.referee_coach</code>.
     */
    public Boolean getRefereeCoach() {
        return this.refereeCoach;
    }

    /**
     * Setter for <code>public.login.referee_coach</code>.
     */
    public void setRefereeCoach(Boolean refereeCoach) {
        this.refereeCoach = refereeCoach;
    }

    /**
     * Getter for <code>public.login.referee</code>.
     */
    public Boolean getReferee() {
        return this.referee;
    }

    /**
     * Setter for <code>public.login.referee</code>.
     */
    public void setReferee(Boolean referee) {
        this.referee = referee;
    }

    /**
     * Getter for <code>public.login.trainer_coach</code>.
     */
    public Boolean getTrainerCoach() {
        return this.trainerCoach;
    }

    /**
     * Setter for <code>public.login.trainer_coach</code>.
     */
    public void setTrainerCoach(Boolean trainerCoach) {
        this.trainerCoach = trainerCoach;
    }

    /**
     * Getter for <code>public.login.trainer</code>.
     */
    public Boolean getTrainer() {
        return this.trainer;
    }

    /**
     * Setter for <code>public.login.trainer</code>.
     */
    public void setTrainer(Boolean trainer) {
        this.trainer = trainer;
    }

    /**
     * Getter for <code>public.login.admin</code>.
     */
    public Boolean getAdmin() {
        return this.admin;
    }

    /**
     * Setter for <code>public.login.admin</code>.
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    /**
     * Getter for <code>public.login.rank</code>.
     */
    public String getRank() {
        return this.rank;
    }

    /**
     * Setter for <code>public.login.rank</code>.
     */
    public void setRank(String rank) {
        this.rank = rank;
    }

    /**
     * Getter for <code>public.login.active</code>.
     */
    public Boolean getActive() {
        return this.active;
    }

    /**
     * Setter for <code>public.login.active</code>.
     */
    public void setActive(Boolean active) {
        this.active = active;
    }

    /**
     * Getter for <code>public.login.referee_coach_plus</code>.
     */
    public Boolean getRefereeCoachPlus() {
        return this.refereeCoachPlus;
    }

    /**
     * Setter for <code>public.login.referee_coach_plus</code>.
     */
    public void setRefereeCoachPlus(Boolean refereeCoachPlus) {
        this.refereeCoachPlus = refereeCoachPlus;
    }

    /**
     * Getter for <code>public.login.username</code>.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>public.login.username</code>.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Login other = (Login) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.lastLogin == null) {
            if (other.lastLogin != null)
                return false;
        }
        else if (!this.lastLogin.equals(other.lastLogin))
            return false;
        if (this.refereeCoach == null) {
            if (other.refereeCoach != null)
                return false;
        }
        else if (!this.refereeCoach.equals(other.refereeCoach))
            return false;
        if (this.referee == null) {
            if (other.referee != null)
                return false;
        }
        else if (!this.referee.equals(other.referee))
            return false;
        if (this.trainerCoach == null) {
            if (other.trainerCoach != null)
                return false;
        }
        else if (!this.trainerCoach.equals(other.trainerCoach))
            return false;
        if (this.trainer == null) {
            if (other.trainer != null)
                return false;
        }
        else if (!this.trainer.equals(other.trainer))
            return false;
        if (this.admin == null) {
            if (other.admin != null)
                return false;
        }
        else if (!this.admin.equals(other.admin))
            return false;
        if (this.rank == null) {
            if (other.rank != null)
                return false;
        }
        else if (!this.rank.equals(other.rank))
            return false;
        if (this.active == null) {
            if (other.active != null)
                return false;
        }
        else if (!this.active.equals(other.active))
            return false;
        if (this.refereeCoachPlus == null) {
            if (other.refereeCoachPlus != null)
                return false;
        }
        else if (!this.refereeCoachPlus.equals(other.refereeCoachPlus))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.lastLogin == null) ? 0 : this.lastLogin.hashCode());
        result = prime * result + ((this.refereeCoach == null) ? 0 : this.refereeCoach.hashCode());
        result = prime * result + ((this.referee == null) ? 0 : this.referee.hashCode());
        result = prime * result + ((this.trainerCoach == null) ? 0 : this.trainerCoach.hashCode());
        result = prime * result + ((this.trainer == null) ? 0 : this.trainer.hashCode());
        result = prime * result + ((this.admin == null) ? 0 : this.admin.hashCode());
        result = prime * result + ((this.rank == null) ? 0 : this.rank.hashCode());
        result = prime * result + ((this.active == null) ? 0 : this.active.hashCode());
        result = prime * result + ((this.refereeCoachPlus == null) ? 0 : this.refereeCoachPlus.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Login (");

        sb.append(id);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(email);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(refereeCoach);
        sb.append(", ").append(referee);
        sb.append(", ").append(trainerCoach);
        sb.append(", ").append(trainer);
        sb.append(", ").append(admin);
        sb.append(", ").append(rank);
        sb.append(", ").append(active);
        sb.append(", ").append(refereeCoachPlus);
        sb.append(", ").append(username);

        sb.append(")");
        return sb.toString();
    }
}
