/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Login implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String basketplanUsername;
    private String firstname;
    private String lastname;
    private String email;
    private LocalDateTime lastLogin;
    private Boolean refereeCoach;
    private Boolean referee;
    private Boolean trainerCoach;
    private Boolean trainer;
    private Boolean admin;

    public Login() {}

    public Login(Login value) {
        this.id = value.id;
        this.basketplanUsername = value.basketplanUsername;
        this.firstname = value.firstname;
        this.lastname = value.lastname;
        this.email = value.email;
        this.lastLogin = value.lastLogin;
        this.refereeCoach = value.refereeCoach;
        this.referee = value.referee;
        this.trainerCoach = value.trainerCoach;
        this.trainer = value.trainer;
        this.admin = value.admin;
    }

    public Login(
        Long id,
        String basketplanUsername,
        String firstname,
        String lastname,
        String email,
        LocalDateTime lastLogin,
        Boolean refereeCoach,
        Boolean referee,
        Boolean trainerCoach,
        Boolean trainer,
        Boolean admin
    ) {
        this.id = id;
        this.basketplanUsername = basketplanUsername;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.lastLogin = lastLogin;
        this.refereeCoach = refereeCoach;
        this.referee = referee;
        this.trainerCoach = trainerCoach;
        this.trainer = trainer;
        this.admin = admin;
    }

    /**
     * Getter for <code>public.login.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.login.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.login.basketplan_username</code>.
     */
    public String getBasketplanUsername() {
        return this.basketplanUsername;
    }

    /**
     * Setter for <code>public.login.basketplan_username</code>.
     */
    public void setBasketplanUsername(String basketplanUsername) {
        this.basketplanUsername = basketplanUsername;
    }

    /**
     * Getter for <code>public.login.firstname</code>.
     */
    public String getFirstname() {
        return this.firstname;
    }

    /**
     * Setter for <code>public.login.firstname</code>.
     */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * Getter for <code>public.login.lastname</code>.
     */
    public String getLastname() {
        return this.lastname;
    }

    /**
     * Setter for <code>public.login.lastname</code>.
     */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * Getter for <code>public.login.email</code>.
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>public.login.email</code>.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>public.login.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return this.lastLogin;
    }

    /**
     * Setter for <code>public.login.last_login</code>.
     */
    public void setLastLogin(LocalDateTime lastLogin) {
        this.lastLogin = lastLogin;
    }

    /**
     * Getter for <code>public.login.referee_coach</code>.
     */
    public Boolean getRefereeCoach() {
        return this.refereeCoach;
    }

    /**
     * Setter for <code>public.login.referee_coach</code>.
     */
    public void setRefereeCoach(Boolean refereeCoach) {
        this.refereeCoach = refereeCoach;
    }

    /**
     * Getter for <code>public.login.referee</code>.
     */
    public Boolean getReferee() {
        return this.referee;
    }

    /**
     * Setter for <code>public.login.referee</code>.
     */
    public void setReferee(Boolean referee) {
        this.referee = referee;
    }

    /**
     * Getter for <code>public.login.trainer_coach</code>.
     */
    public Boolean getTrainerCoach() {
        return this.trainerCoach;
    }

    /**
     * Setter for <code>public.login.trainer_coach</code>.
     */
    public void setTrainerCoach(Boolean trainerCoach) {
        this.trainerCoach = trainerCoach;
    }

    /**
     * Getter for <code>public.login.trainer</code>.
     */
    public Boolean getTrainer() {
        return this.trainer;
    }

    /**
     * Setter for <code>public.login.trainer</code>.
     */
    public void setTrainer(Boolean trainer) {
        this.trainer = trainer;
    }

    /**
     * Getter for <code>public.login.admin</code>.
     */
    public Boolean getAdmin() {
        return this.admin;
    }

    /**
     * Setter for <code>public.login.admin</code>.
     */
    public void setAdmin(Boolean admin) {
        this.admin = admin;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Login other = (Login) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.basketplanUsername == null) {
            if (other.basketplanUsername != null)
                return false;
        }
        else if (!this.basketplanUsername.equals(other.basketplanUsername))
            return false;
        if (this.firstname == null) {
            if (other.firstname != null)
                return false;
        }
        else if (!this.firstname.equals(other.firstname))
            return false;
        if (this.lastname == null) {
            if (other.lastname != null)
                return false;
        }
        else if (!this.lastname.equals(other.lastname))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.lastLogin == null) {
            if (other.lastLogin != null)
                return false;
        }
        else if (!this.lastLogin.equals(other.lastLogin))
            return false;
        if (this.refereeCoach == null) {
            if (other.refereeCoach != null)
                return false;
        }
        else if (!this.refereeCoach.equals(other.refereeCoach))
            return false;
        if (this.referee == null) {
            if (other.referee != null)
                return false;
        }
        else if (!this.referee.equals(other.referee))
            return false;
        if (this.trainerCoach == null) {
            if (other.trainerCoach != null)
                return false;
        }
        else if (!this.trainerCoach.equals(other.trainerCoach))
            return false;
        if (this.trainer == null) {
            if (other.trainer != null)
                return false;
        }
        else if (!this.trainer.equals(other.trainer))
            return false;
        if (this.admin == null) {
            if (other.admin != null)
                return false;
        }
        else if (!this.admin.equals(other.admin))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.basketplanUsername == null) ? 0 : this.basketplanUsername.hashCode());
        result = prime * result + ((this.firstname == null) ? 0 : this.firstname.hashCode());
        result = prime * result + ((this.lastname == null) ? 0 : this.lastname.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.lastLogin == null) ? 0 : this.lastLogin.hashCode());
        result = prime * result + ((this.refereeCoach == null) ? 0 : this.refereeCoach.hashCode());
        result = prime * result + ((this.referee == null) ? 0 : this.referee.hashCode());
        result = prime * result + ((this.trainerCoach == null) ? 0 : this.trainerCoach.hashCode());
        result = prime * result + ((this.trainer == null) ? 0 : this.trainer.hashCode());
        result = prime * result + ((this.admin == null) ? 0 : this.admin.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Login (");

        sb.append(id);
        sb.append(", ").append(basketplanUsername);
        sb.append(", ").append(firstname);
        sb.append(", ").append(lastname);
        sb.append(", ").append(email);
        sb.append(", ").append(lastLogin);
        sb.append(", ").append(refereeCoach);
        sb.append(", ").append(referee);
        sb.append(", ").append(trainerCoach);
        sb.append(", ").append(trainer);
        sb.append(", ").append(admin);

        sb.append(")");
        return sb.toString();
    }
}
