/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoComment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long reportId;
    private Long timestampInSeconds;
    private String comment;
    private LocalDateTime createdAt;
    private Long createdBy;
    private Boolean requiresReply;

    public ReportVideoComment() {}

    public ReportVideoComment(ReportVideoComment value) {
        this.id = value.id;
        this.reportId = value.reportId;
        this.timestampInSeconds = value.timestampInSeconds;
        this.comment = value.comment;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.requiresReply = value.requiresReply;
    }

    public ReportVideoComment(
        Long id,
        Long reportId,
        Long timestampInSeconds,
        String comment,
        LocalDateTime createdAt,
        Long createdBy,
        Boolean requiresReply
    ) {
        this.id = id;
        this.reportId = reportId;
        this.timestampInSeconds = timestampInSeconds;
        this.comment = comment;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.requiresReply = requiresReply;
    }

    /**
     * Getter for <code>public.report_video_comment.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.report_video_comment.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.report_video_comment.report_id</code>.
     */
    public Long getReportId() {
        return this.reportId;
    }

    /**
     * Setter for <code>public.report_video_comment.report_id</code>.
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * Getter for <code>public.report_video_comment.timestamp_in_seconds</code>.
     */
    public Long getTimestampInSeconds() {
        return this.timestampInSeconds;
    }

    /**
     * Setter for <code>public.report_video_comment.timestamp_in_seconds</code>.
     */
    public void setTimestampInSeconds(Long timestampInSeconds) {
        this.timestampInSeconds = timestampInSeconds;
    }

    /**
     * Getter for <code>public.report_video_comment.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>public.report_video_comment.comment</code>.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for <code>public.report_video_comment.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.report_video_comment.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.report_video_comment.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.report_video_comment.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.report_video_comment.requires_reply</code>.
     */
    public Boolean getRequiresReply() {
        return this.requiresReply;
    }

    /**
     * Setter for <code>public.report_video_comment.requires_reply</code>.
     */
    public void setRequiresReply(Boolean requiresReply) {
        this.requiresReply = requiresReply;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportVideoComment other = (ReportVideoComment) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.reportId == null) {
            if (other.reportId != null)
                return false;
        }
        else if (!this.reportId.equals(other.reportId))
            return false;
        if (this.timestampInSeconds == null) {
            if (other.timestampInSeconds != null)
                return false;
        }
        else if (!this.timestampInSeconds.equals(other.timestampInSeconds))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.requiresReply == null) {
            if (other.requiresReply != null)
                return false;
        }
        else if (!this.requiresReply.equals(other.requiresReply))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.reportId == null) ? 0 : this.reportId.hashCode());
        result = prime * result + ((this.timestampInSeconds == null) ? 0 : this.timestampInSeconds.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.requiresReply == null) ? 0 : this.requiresReply.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportVideoComment (");

        sb.append(id);
        sb.append(", ").append(reportId);
        sb.append(", ").append(timestampInSeconds);
        sb.append(", ").append(comment);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(requiresReply);

        sb.append(")");
        return sb.toString();
    }
}
