/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentTag implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long reportVideoCommentId;
    private Long tagId;

    public ReportVideoCommentTag() {}

    public ReportVideoCommentTag(ReportVideoCommentTag value) {
        this.reportVideoCommentId = value.reportVideoCommentId;
        this.tagId = value.tagId;
    }

    public ReportVideoCommentTag(
        Long reportVideoCommentId,
        Long tagId
    ) {
        this.reportVideoCommentId = reportVideoCommentId;
        this.tagId = tagId;
    }

    /**
     * Getter for
     * <code>public.report_video_comment_tag.report_video_comment_id</code>.
     */
    public Long getReportVideoCommentId() {
        return this.reportVideoCommentId;
    }

    /**
     * Setter for
     * <code>public.report_video_comment_tag.report_video_comment_id</code>.
     */
    public void setReportVideoCommentId(Long reportVideoCommentId) {
        this.reportVideoCommentId = reportVideoCommentId;
    }

    /**
     * Getter for <code>public.report_video_comment_tag.tag_id</code>.
     */
    public Long getTagId() {
        return this.tagId;
    }

    /**
     * Setter for <code>public.report_video_comment_tag.tag_id</code>.
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportVideoCommentTag other = (ReportVideoCommentTag) obj;
        if (this.reportVideoCommentId == null) {
            if (other.reportVideoCommentId != null)
                return false;
        }
        else if (!this.reportVideoCommentId.equals(other.reportVideoCommentId))
            return false;
        if (this.tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!this.tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reportVideoCommentId == null) ? 0 : this.reportVideoCommentId.hashCode());
        result = prime * result + ((this.tagId == null) ? 0 : this.tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportVideoCommentTag (");

        sb.append(reportVideoCommentId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
