/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentRef implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long reportId;
    private Long reportVideoCommentId;
    private Boolean requiresReply;

    public ReportVideoCommentRef() {}

    public ReportVideoCommentRef(ReportVideoCommentRef value) {
        this.reportId = value.reportId;
        this.reportVideoCommentId = value.reportVideoCommentId;
        this.requiresReply = value.requiresReply;
    }

    public ReportVideoCommentRef(
        Long reportId,
        Long reportVideoCommentId,
        Boolean requiresReply
    ) {
        this.reportId = reportId;
        this.reportVideoCommentId = reportVideoCommentId;
        this.requiresReply = requiresReply;
    }

    /**
     * Getter for <code>public.report_video_comment_ref.report_id</code>.
     */
    public Long getReportId() {
        return this.reportId;
    }

    /**
     * Setter for <code>public.report_video_comment_ref.report_id</code>.
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * Getter for
     * <code>public.report_video_comment_ref.report_video_comment_id</code>.
     */
    public Long getReportVideoCommentId() {
        return this.reportVideoCommentId;
    }

    /**
     * Setter for
     * <code>public.report_video_comment_ref.report_video_comment_id</code>.
     */
    public void setReportVideoCommentId(Long reportVideoCommentId) {
        this.reportVideoCommentId = reportVideoCommentId;
    }

    /**
     * Getter for <code>public.report_video_comment_ref.requires_reply</code>.
     */
    public Boolean getRequiresReply() {
        return this.requiresReply;
    }

    /**
     * Setter for <code>public.report_video_comment_ref.requires_reply</code>.
     */
    public void setRequiresReply(Boolean requiresReply) {
        this.requiresReply = requiresReply;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportVideoCommentRef other = (ReportVideoCommentRef) obj;
        if (this.reportId == null) {
            if (other.reportId != null)
                return false;
        }
        else if (!this.reportId.equals(other.reportId))
            return false;
        if (this.reportVideoCommentId == null) {
            if (other.reportVideoCommentId != null)
                return false;
        }
        else if (!this.reportVideoCommentId.equals(other.reportVideoCommentId))
            return false;
        if (this.requiresReply == null) {
            if (other.requiresReply != null)
                return false;
        }
        else if (!this.requiresReply.equals(other.requiresReply))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reportId == null) ? 0 : this.reportId.hashCode());
        result = prime * result + ((this.reportVideoCommentId == null) ? 0 : this.reportVideoCommentId.hashCode());
        result = prime * result + ((this.requiresReply == null) ? 0 : this.requiresReply.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportVideoCommentRef (");

        sb.append(reportId);
        sb.append(", ").append(reportVideoCommentId);
        sb.append(", ").append(requiresReply);

        sb.append(")");
        return sb.toString();
    }
}
