/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportComment implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long reportId;
    private String type;
    private String comment;
    private BigDecimal score;

    public ReportComment() {}

    public ReportComment(ReportComment value) {
        this.id = value.id;
        this.reportId = value.reportId;
        this.type = value.type;
        this.comment = value.comment;
        this.score = value.score;
    }

    public ReportComment(
        Long id,
        Long reportId,
        String type,
        String comment,
        BigDecimal score
    ) {
        this.id = id;
        this.reportId = reportId;
        this.type = type;
        this.comment = comment;
        this.score = score;
    }

    /**
     * Getter for <code>public.report_comment.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.report_comment.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.report_comment.report_id</code>.
     */
    public Long getReportId() {
        return this.reportId;
    }

    /**
     * Setter for <code>public.report_comment.report_id</code>.
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * Getter for <code>public.report_comment.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.report_comment.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.report_comment.comment</code>.
     */
    public String getComment() {
        return this.comment;
    }

    /**
     * Setter for <code>public.report_comment.comment</code>.
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Getter for <code>public.report_comment.score</code>.
     */
    public BigDecimal getScore() {
        return this.score;
    }

    /**
     * Setter for <code>public.report_comment.score</code>.
     */
    public void setScore(BigDecimal score) {
        this.score = score;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportComment other = (ReportComment) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.reportId == null) {
            if (other.reportId != null)
                return false;
        }
        else if (!this.reportId.equals(other.reportId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.comment == null) {
            if (other.comment != null)
                return false;
        }
        else if (!this.comment.equals(other.comment))
            return false;
        if (this.score == null) {
            if (other.score != null)
                return false;
        }
        else if (!this.score.equals(other.score))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.reportId == null) ? 0 : this.reportId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.comment == null) ? 0 : this.comment.hashCode());
        result = prime * result + ((this.score == null) ? 0 : this.score.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportComment (");

        sb.append(id);
        sb.append(", ").append(reportId);
        sb.append(", ").append(type);
        sb.append(", ").append(comment);
        sb.append(", ").append(score);

        sb.append(")");
        return sb.toString();
    }
}
