/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportCommentsLastRead implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long reportId;
    private Long userId;
    private LocalDateTime lastReadAt;

    public ReportCommentsLastRead() {}

    public ReportCommentsLastRead(ReportCommentsLastRead value) {
        this.reportId = value.reportId;
        this.userId = value.userId;
        this.lastReadAt = value.lastReadAt;
    }

    public ReportCommentsLastRead(
        Long reportId,
        Long userId,
        LocalDateTime lastReadAt
    ) {
        this.reportId = reportId;
        this.userId = userId;
        this.lastReadAt = lastReadAt;
    }

    /**
     * Getter for <code>public.report_comments_last_read.report_id</code>.
     */
    public Long getReportId() {
        return this.reportId;
    }

    /**
     * Setter for <code>public.report_comments_last_read.report_id</code>.
     */
    public void setReportId(Long reportId) {
        this.reportId = reportId;
    }

    /**
     * Getter for <code>public.report_comments_last_read.user_id</code>.
     */
    public Long getUserId() {
        return this.userId;
    }

    /**
     * Setter for <code>public.report_comments_last_read.user_id</code>.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Getter for <code>public.report_comments_last_read.last_read_at</code>.
     */
    public LocalDateTime getLastReadAt() {
        return this.lastReadAt;
    }

    /**
     * Setter for <code>public.report_comments_last_read.last_read_at</code>.
     */
    public void setLastReadAt(LocalDateTime lastReadAt) {
        this.lastReadAt = lastReadAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportCommentsLastRead other = (ReportCommentsLastRead) obj;
        if (this.reportId == null) {
            if (other.reportId != null)
                return false;
        }
        else if (!this.reportId.equals(other.reportId))
            return false;
        if (this.userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!this.userId.equals(other.userId))
            return false;
        if (this.lastReadAt == null) {
            if (other.lastReadAt != null)
                return false;
        }
        else if (!this.lastReadAt.equals(other.lastReadAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.reportId == null) ? 0 : this.reportId.hashCode());
        result = prime * result + ((this.userId == null) ? 0 : this.userId.hashCode());
        result = prime * result + ((this.lastReadAt == null) ? 0 : this.lastReadAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportCommentsLastRead (");

        sb.append(reportId);
        sb.append(", ").append(userId);
        sb.append(", ").append(lastReadAt);

        sb.append(")");
        return sb.toString();
    }
}
