/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentReply implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long reportVideoCommentId;
    private String reply;
    private LocalDateTime createdAt;
    private Long createdBy;

    public ReportVideoCommentReply() {}

    public ReportVideoCommentReply(ReportVideoCommentReply value) {
        this.id = value.id;
        this.reportVideoCommentId = value.reportVideoCommentId;
        this.reply = value.reply;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
    }

    public ReportVideoCommentReply(
        Long id,
        Long reportVideoCommentId,
        String reply,
        LocalDateTime createdAt,
        Long createdBy
    ) {
        this.id = id;
        this.reportVideoCommentId = reportVideoCommentId;
        this.reply = reply;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.report_video_comment_reply.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.report_video_comment_reply.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for
     * <code>public.report_video_comment_reply.report_video_comment_id</code>.
     */
    public Long getReportVideoCommentId() {
        return this.reportVideoCommentId;
    }

    /**
     * Setter for
     * <code>public.report_video_comment_reply.report_video_comment_id</code>.
     */
    public void setReportVideoCommentId(Long reportVideoCommentId) {
        this.reportVideoCommentId = reportVideoCommentId;
    }

    /**
     * Getter for <code>public.report_video_comment_reply.reply</code>.
     */
    public String getReply() {
        return this.reply;
    }

    /**
     * Setter for <code>public.report_video_comment_reply.reply</code>.
     */
    public void setReply(String reply) {
        this.reply = reply;
    }

    /**
     * Getter for <code>public.report_video_comment_reply.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.report_video_comment_reply.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.report_video_comment_reply.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.report_video_comment_reply.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportVideoCommentReply other = (ReportVideoCommentReply) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.reportVideoCommentId == null) {
            if (other.reportVideoCommentId != null)
                return false;
        }
        else if (!this.reportVideoCommentId.equals(other.reportVideoCommentId))
            return false;
        if (this.reply == null) {
            if (other.reply != null)
                return false;
        }
        else if (!this.reply.equals(other.reply))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.reportVideoCommentId == null) ? 0 : this.reportVideoCommentId.hashCode());
        result = prime * result + ((this.reply == null) ? 0 : this.reply.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportVideoCommentReply (");

        sb.append(id);
        sb.append(", ").append(reportVideoCommentId);
        sb.append(", ").append(reply);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);

        sb.append(")");
        return sb.toString();
    }
}
