/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportCriteria implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private Long reportCommentId;
    private String type;
    private String state;

    public ReportCriteria() {}

    public ReportCriteria(ReportCriteria value) {
        this.id = value.id;
        this.reportCommentId = value.reportCommentId;
        this.type = value.type;
        this.state = value.state;
    }

    public ReportCriteria(
        Long id,
        Long reportCommentId,
        String type,
        String state
    ) {
        this.id = id;
        this.reportCommentId = reportCommentId;
        this.type = type;
        this.state = state;
    }

    /**
     * Getter for <code>public.report_criteria.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.report_criteria.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.report_criteria.report_comment_id</code>.
     */
    public Long getReportCommentId() {
        return this.reportCommentId;
    }

    /**
     * Setter for <code>public.report_criteria.report_comment_id</code>.
     */
    public void setReportCommentId(Long reportCommentId) {
        this.reportCommentId = reportCommentId;
    }

    /**
     * Getter for <code>public.report_criteria.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>public.report_criteria.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>public.report_criteria.state</code>.
     */
    public String getState() {
        return this.state;
    }

    /**
     * Setter for <code>public.report_criteria.state</code>.
     */
    public void setState(String state) {
        this.state = state;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportCriteria other = (ReportCriteria) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.reportCommentId == null) {
            if (other.reportCommentId != null)
                return false;
        }
        else if (!this.reportCommentId.equals(other.reportCommentId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.state == null) {
            if (other.state != null)
                return false;
        }
        else if (!this.state.equals(other.state))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.reportCommentId == null) ? 0 : this.reportCommentId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.state == null) ? 0 : this.state.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportCriteria (");

        sb.append(id);
        sb.append(", ").append(reportCommentId);
        sb.append(", ").append(type);
        sb.append(", ").append(state);

        sb.append(")");
        return sb.toString();
    }
}
