/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Report implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String externalId;
    private String reportType;
    private Long coachId;
    private String coachName;
    private Long reporteeId;
    private String reporteeName;
    private String reporteeRank;
    private String gameNumber;
    private String gameCompetition;
    private LocalDate gameDate;
    private String gameResult;
    private String gameHomeTeam;
    private Integer gameHomeTeamId;
    private String gameGuestTeam;
    private Integer gameGuestTeamId;
    private Long gameReferee1Id;
    private String gameReferee1Name;
    private Long gameReferee2Id;
    private String gameReferee2Name;
    private Long gameReferee3Id;
    private String gameReferee3Name;
    private String gameVideoUrl;
    private BigDecimal overallScore;
    private LocalDateTime createdAt;
    private Long createdBy;
    private LocalDateTime updatedAt;
    private Long updatedBy;
    private LocalDateTime finishedAt;
    private Long finishedBy;
    private Boolean reminderSent;
    private String gameReferee1Rank;
    private String gameReferee2Rank;
    private String gameReferee3Rank;

    public Report() {}

    public Report(Report value) {
        this.id = value.id;
        this.externalId = value.externalId;
        this.reportType = value.reportType;
        this.coachId = value.coachId;
        this.coachName = value.coachName;
        this.reporteeId = value.reporteeId;
        this.reporteeName = value.reporteeName;
        this.reporteeRank = value.reporteeRank;
        this.gameNumber = value.gameNumber;
        this.gameCompetition = value.gameCompetition;
        this.gameDate = value.gameDate;
        this.gameResult = value.gameResult;
        this.gameHomeTeam = value.gameHomeTeam;
        this.gameHomeTeamId = value.gameHomeTeamId;
        this.gameGuestTeam = value.gameGuestTeam;
        this.gameGuestTeamId = value.gameGuestTeamId;
        this.gameReferee1Id = value.gameReferee1Id;
        this.gameReferee1Name = value.gameReferee1Name;
        this.gameReferee2Id = value.gameReferee2Id;
        this.gameReferee2Name = value.gameReferee2Name;
        this.gameReferee3Id = value.gameReferee3Id;
        this.gameReferee3Name = value.gameReferee3Name;
        this.gameVideoUrl = value.gameVideoUrl;
        this.overallScore = value.overallScore;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
        this.updatedAt = value.updatedAt;
        this.updatedBy = value.updatedBy;
        this.finishedAt = value.finishedAt;
        this.finishedBy = value.finishedBy;
        this.reminderSent = value.reminderSent;
        this.gameReferee1Rank = value.gameReferee1Rank;
        this.gameReferee2Rank = value.gameReferee2Rank;
        this.gameReferee3Rank = value.gameReferee3Rank;
    }

    public Report(
        Long id,
        String externalId,
        String reportType,
        Long coachId,
        String coachName,
        Long reporteeId,
        String reporteeName,
        String reporteeRank,
        String gameNumber,
        String gameCompetition,
        LocalDate gameDate,
        String gameResult,
        String gameHomeTeam,
        Integer gameHomeTeamId,
        String gameGuestTeam,
        Integer gameGuestTeamId,
        Long gameReferee1Id,
        String gameReferee1Name,
        Long gameReferee2Id,
        String gameReferee2Name,
        Long gameReferee3Id,
        String gameReferee3Name,
        String gameVideoUrl,
        BigDecimal overallScore,
        LocalDateTime createdAt,
        Long createdBy,
        LocalDateTime updatedAt,
        Long updatedBy,
        LocalDateTime finishedAt,
        Long finishedBy,
        Boolean reminderSent,
        String gameReferee1Rank,
        String gameReferee2Rank,
        String gameReferee3Rank
    ) {
        this.id = id;
        this.externalId = externalId;
        this.reportType = reportType;
        this.coachId = coachId;
        this.coachName = coachName;
        this.reporteeId = reporteeId;
        this.reporteeName = reporteeName;
        this.reporteeRank = reporteeRank;
        this.gameNumber = gameNumber;
        this.gameCompetition = gameCompetition;
        this.gameDate = gameDate;
        this.gameResult = gameResult;
        this.gameHomeTeam = gameHomeTeam;
        this.gameHomeTeamId = gameHomeTeamId;
        this.gameGuestTeam = gameGuestTeam;
        this.gameGuestTeamId = gameGuestTeamId;
        this.gameReferee1Id = gameReferee1Id;
        this.gameReferee1Name = gameReferee1Name;
        this.gameReferee2Id = gameReferee2Id;
        this.gameReferee2Name = gameReferee2Name;
        this.gameReferee3Id = gameReferee3Id;
        this.gameReferee3Name = gameReferee3Name;
        this.gameVideoUrl = gameVideoUrl;
        this.overallScore = overallScore;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.finishedAt = finishedAt;
        this.finishedBy = finishedBy;
        this.reminderSent = reminderSent;
        this.gameReferee1Rank = gameReferee1Rank;
        this.gameReferee2Rank = gameReferee2Rank;
        this.gameReferee3Rank = gameReferee3Rank;
    }

    /**
     * Getter for <code>public.report.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.report.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.report.external_id</code>.
     */
    public String getExternalId() {
        return this.externalId;
    }

    /**
     * Setter for <code>public.report.external_id</code>.
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Getter for <code>public.report.report_type</code>.
     */
    public String getReportType() {
        return this.reportType;
    }

    /**
     * Setter for <code>public.report.report_type</code>.
     */
    public void setReportType(String reportType) {
        this.reportType = reportType;
    }

    /**
     * Getter for <code>public.report.coach_id</code>.
     */
    public Long getCoachId() {
        return this.coachId;
    }

    /**
     * Setter for <code>public.report.coach_id</code>.
     */
    public void setCoachId(Long coachId) {
        this.coachId = coachId;
    }

    /**
     * Getter for <code>public.report.coach_name</code>.
     */
    public String getCoachName() {
        return this.coachName;
    }

    /**
     * Setter for <code>public.report.coach_name</code>.
     */
    public void setCoachName(String coachName) {
        this.coachName = coachName;
    }

    /**
     * Getter for <code>public.report.reportee_id</code>.
     */
    public Long getReporteeId() {
        return this.reporteeId;
    }

    /**
     * Setter for <code>public.report.reportee_id</code>.
     */
    public void setReporteeId(Long reporteeId) {
        this.reporteeId = reporteeId;
    }

    /**
     * Getter for <code>public.report.reportee_name</code>.
     */
    public String getReporteeName() {
        return this.reporteeName;
    }

    /**
     * Setter for <code>public.report.reportee_name</code>.
     */
    public void setReporteeName(String reporteeName) {
        this.reporteeName = reporteeName;
    }

    /**
     * Getter for <code>public.report.reportee_rank</code>.
     */
    public String getReporteeRank() {
        return this.reporteeRank;
    }

    /**
     * Setter for <code>public.report.reportee_rank</code>.
     */
    public void setReporteeRank(String reporteeRank) {
        this.reporteeRank = reporteeRank;
    }

    /**
     * Getter for <code>public.report.game_number</code>.
     */
    public String getGameNumber() {
        return this.gameNumber;
    }

    /**
     * Setter for <code>public.report.game_number</code>.
     */
    public void setGameNumber(String gameNumber) {
        this.gameNumber = gameNumber;
    }

    /**
     * Getter for <code>public.report.game_competition</code>.
     */
    public String getGameCompetition() {
        return this.gameCompetition;
    }

    /**
     * Setter for <code>public.report.game_competition</code>.
     */
    public void setGameCompetition(String gameCompetition) {
        this.gameCompetition = gameCompetition;
    }

    /**
     * Getter for <code>public.report.game_date</code>.
     */
    public LocalDate getGameDate() {
        return this.gameDate;
    }

    /**
     * Setter for <code>public.report.game_date</code>.
     */
    public void setGameDate(LocalDate gameDate) {
        this.gameDate = gameDate;
    }

    /**
     * Getter for <code>public.report.game_result</code>.
     */
    public String getGameResult() {
        return this.gameResult;
    }

    /**
     * Setter for <code>public.report.game_result</code>.
     */
    public void setGameResult(String gameResult) {
        this.gameResult = gameResult;
    }

    /**
     * Getter for <code>public.report.game_home_team</code>.
     */
    public String getGameHomeTeam() {
        return this.gameHomeTeam;
    }

    /**
     * Setter for <code>public.report.game_home_team</code>.
     */
    public void setGameHomeTeam(String gameHomeTeam) {
        this.gameHomeTeam = gameHomeTeam;
    }

    /**
     * Getter for <code>public.report.game_home_team_id</code>.
     */
    public Integer getGameHomeTeamId() {
        return this.gameHomeTeamId;
    }

    /**
     * Setter for <code>public.report.game_home_team_id</code>.
     */
    public void setGameHomeTeamId(Integer gameHomeTeamId) {
        this.gameHomeTeamId = gameHomeTeamId;
    }

    /**
     * Getter for <code>public.report.game_guest_team</code>.
     */
    public String getGameGuestTeam() {
        return this.gameGuestTeam;
    }

    /**
     * Setter for <code>public.report.game_guest_team</code>.
     */
    public void setGameGuestTeam(String gameGuestTeam) {
        this.gameGuestTeam = gameGuestTeam;
    }

    /**
     * Getter for <code>public.report.game_guest_team_id</code>.
     */
    public Integer getGameGuestTeamId() {
        return this.gameGuestTeamId;
    }

    /**
     * Setter for <code>public.report.game_guest_team_id</code>.
     */
    public void setGameGuestTeamId(Integer gameGuestTeamId) {
        this.gameGuestTeamId = gameGuestTeamId;
    }

    /**
     * Getter for <code>public.report.game_referee1_id</code>.
     */
    public Long getGameReferee1Id() {
        return this.gameReferee1Id;
    }

    /**
     * Setter for <code>public.report.game_referee1_id</code>.
     */
    public void setGameReferee1Id(Long gameReferee1Id) {
        this.gameReferee1Id = gameReferee1Id;
    }

    /**
     * Getter for <code>public.report.game_referee1_name</code>.
     */
    public String getGameReferee1Name() {
        return this.gameReferee1Name;
    }

    /**
     * Setter for <code>public.report.game_referee1_name</code>.
     */
    public void setGameReferee1Name(String gameReferee1Name) {
        this.gameReferee1Name = gameReferee1Name;
    }

    /**
     * Getter for <code>public.report.game_referee2_id</code>.
     */
    public Long getGameReferee2Id() {
        return this.gameReferee2Id;
    }

    /**
     * Setter for <code>public.report.game_referee2_id</code>.
     */
    public void setGameReferee2Id(Long gameReferee2Id) {
        this.gameReferee2Id = gameReferee2Id;
    }

    /**
     * Getter for <code>public.report.game_referee2_name</code>.
     */
    public String getGameReferee2Name() {
        return this.gameReferee2Name;
    }

    /**
     * Setter for <code>public.report.game_referee2_name</code>.
     */
    public void setGameReferee2Name(String gameReferee2Name) {
        this.gameReferee2Name = gameReferee2Name;
    }

    /**
     * Getter for <code>public.report.game_referee3_id</code>.
     */
    public Long getGameReferee3Id() {
        return this.gameReferee3Id;
    }

    /**
     * Setter for <code>public.report.game_referee3_id</code>.
     */
    public void setGameReferee3Id(Long gameReferee3Id) {
        this.gameReferee3Id = gameReferee3Id;
    }

    /**
     * Getter for <code>public.report.game_referee3_name</code>.
     */
    public String getGameReferee3Name() {
        return this.gameReferee3Name;
    }

    /**
     * Setter for <code>public.report.game_referee3_name</code>.
     */
    public void setGameReferee3Name(String gameReferee3Name) {
        this.gameReferee3Name = gameReferee3Name;
    }

    /**
     * Getter for <code>public.report.game_video_url</code>.
     */
    public String getGameVideoUrl() {
        return this.gameVideoUrl;
    }

    /**
     * Setter for <code>public.report.game_video_url</code>.
     */
    public void setGameVideoUrl(String gameVideoUrl) {
        this.gameVideoUrl = gameVideoUrl;
    }

    /**
     * Getter for <code>public.report.overall_score</code>.
     */
    public BigDecimal getOverallScore() {
        return this.overallScore;
    }

    /**
     * Setter for <code>public.report.overall_score</code>.
     */
    public void setOverallScore(BigDecimal overallScore) {
        this.overallScore = overallScore;
    }

    /**
     * Getter for <code>public.report.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.report.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.report.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.report.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.report.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>public.report.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>public.report.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return this.updatedBy;
    }

    /**
     * Setter for <code>public.report.updated_by</code>.
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * Getter for <code>public.report.finished_at</code>.
     */
    public LocalDateTime getFinishedAt() {
        return this.finishedAt;
    }

    /**
     * Setter for <code>public.report.finished_at</code>.
     */
    public void setFinishedAt(LocalDateTime finishedAt) {
        this.finishedAt = finishedAt;
    }

    /**
     * Getter for <code>public.report.finished_by</code>.
     */
    public Long getFinishedBy() {
        return this.finishedBy;
    }

    /**
     * Setter for <code>public.report.finished_by</code>.
     */
    public void setFinishedBy(Long finishedBy) {
        this.finishedBy = finishedBy;
    }

    /**
     * Getter for <code>public.report.reminder_sent</code>.
     */
    public Boolean getReminderSent() {
        return this.reminderSent;
    }

    /**
     * Setter for <code>public.report.reminder_sent</code>.
     */
    public void setReminderSent(Boolean reminderSent) {
        this.reminderSent = reminderSent;
    }

    /**
     * Getter for <code>public.report.game_referee1_rank</code>.
     */
    public String getGameReferee1Rank() {
        return this.gameReferee1Rank;
    }

    /**
     * Setter for <code>public.report.game_referee1_rank</code>.
     */
    public void setGameReferee1Rank(String gameReferee1Rank) {
        this.gameReferee1Rank = gameReferee1Rank;
    }

    /**
     * Getter for <code>public.report.game_referee2_rank</code>.
     */
    public String getGameReferee2Rank() {
        return this.gameReferee2Rank;
    }

    /**
     * Setter for <code>public.report.game_referee2_rank</code>.
     */
    public void setGameReferee2Rank(String gameReferee2Rank) {
        this.gameReferee2Rank = gameReferee2Rank;
    }

    /**
     * Getter for <code>public.report.game_referee3_rank</code>.
     */
    public String getGameReferee3Rank() {
        return this.gameReferee3Rank;
    }

    /**
     * Setter for <code>public.report.game_referee3_rank</code>.
     */
    public void setGameReferee3Rank(String gameReferee3Rank) {
        this.gameReferee3Rank = gameReferee3Rank;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Report other = (Report) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.externalId == null) {
            if (other.externalId != null)
                return false;
        }
        else if (!this.externalId.equals(other.externalId))
            return false;
        if (this.reportType == null) {
            if (other.reportType != null)
                return false;
        }
        else if (!this.reportType.equals(other.reportType))
            return false;
        if (this.coachId == null) {
            if (other.coachId != null)
                return false;
        }
        else if (!this.coachId.equals(other.coachId))
            return false;
        if (this.coachName == null) {
            if (other.coachName != null)
                return false;
        }
        else if (!this.coachName.equals(other.coachName))
            return false;
        if (this.reporteeId == null) {
            if (other.reporteeId != null)
                return false;
        }
        else if (!this.reporteeId.equals(other.reporteeId))
            return false;
        if (this.reporteeName == null) {
            if (other.reporteeName != null)
                return false;
        }
        else if (!this.reporteeName.equals(other.reporteeName))
            return false;
        if (this.reporteeRank == null) {
            if (other.reporteeRank != null)
                return false;
        }
        else if (!this.reporteeRank.equals(other.reporteeRank))
            return false;
        if (this.gameNumber == null) {
            if (other.gameNumber != null)
                return false;
        }
        else if (!this.gameNumber.equals(other.gameNumber))
            return false;
        if (this.gameCompetition == null) {
            if (other.gameCompetition != null)
                return false;
        }
        else if (!this.gameCompetition.equals(other.gameCompetition))
            return false;
        if (this.gameDate == null) {
            if (other.gameDate != null)
                return false;
        }
        else if (!this.gameDate.equals(other.gameDate))
            return false;
        if (this.gameResult == null) {
            if (other.gameResult != null)
                return false;
        }
        else if (!this.gameResult.equals(other.gameResult))
            return false;
        if (this.gameHomeTeam == null) {
            if (other.gameHomeTeam != null)
                return false;
        }
        else if (!this.gameHomeTeam.equals(other.gameHomeTeam))
            return false;
        if (this.gameHomeTeamId == null) {
            if (other.gameHomeTeamId != null)
                return false;
        }
        else if (!this.gameHomeTeamId.equals(other.gameHomeTeamId))
            return false;
        if (this.gameGuestTeam == null) {
            if (other.gameGuestTeam != null)
                return false;
        }
        else if (!this.gameGuestTeam.equals(other.gameGuestTeam))
            return false;
        if (this.gameGuestTeamId == null) {
            if (other.gameGuestTeamId != null)
                return false;
        }
        else if (!this.gameGuestTeamId.equals(other.gameGuestTeamId))
            return false;
        if (this.gameReferee1Id == null) {
            if (other.gameReferee1Id != null)
                return false;
        }
        else if (!this.gameReferee1Id.equals(other.gameReferee1Id))
            return false;
        if (this.gameReferee1Name == null) {
            if (other.gameReferee1Name != null)
                return false;
        }
        else if (!this.gameReferee1Name.equals(other.gameReferee1Name))
            return false;
        if (this.gameReferee2Id == null) {
            if (other.gameReferee2Id != null)
                return false;
        }
        else if (!this.gameReferee2Id.equals(other.gameReferee2Id))
            return false;
        if (this.gameReferee2Name == null) {
            if (other.gameReferee2Name != null)
                return false;
        }
        else if (!this.gameReferee2Name.equals(other.gameReferee2Name))
            return false;
        if (this.gameReferee3Id == null) {
            if (other.gameReferee3Id != null)
                return false;
        }
        else if (!this.gameReferee3Id.equals(other.gameReferee3Id))
            return false;
        if (this.gameReferee3Name == null) {
            if (other.gameReferee3Name != null)
                return false;
        }
        else if (!this.gameReferee3Name.equals(other.gameReferee3Name))
            return false;
        if (this.gameVideoUrl == null) {
            if (other.gameVideoUrl != null)
                return false;
        }
        else if (!this.gameVideoUrl.equals(other.gameVideoUrl))
            return false;
        if (this.overallScore == null) {
            if (other.overallScore != null)
                return false;
        }
        else if (!this.overallScore.equals(other.overallScore))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        if (this.updatedBy == null) {
            if (other.updatedBy != null)
                return false;
        }
        else if (!this.updatedBy.equals(other.updatedBy))
            return false;
        if (this.finishedAt == null) {
            if (other.finishedAt != null)
                return false;
        }
        else if (!this.finishedAt.equals(other.finishedAt))
            return false;
        if (this.finishedBy == null) {
            if (other.finishedBy != null)
                return false;
        }
        else if (!this.finishedBy.equals(other.finishedBy))
            return false;
        if (this.reminderSent == null) {
            if (other.reminderSent != null)
                return false;
        }
        else if (!this.reminderSent.equals(other.reminderSent))
            return false;
        if (this.gameReferee1Rank == null) {
            if (other.gameReferee1Rank != null)
                return false;
        }
        else if (!this.gameReferee1Rank.equals(other.gameReferee1Rank))
            return false;
        if (this.gameReferee2Rank == null) {
            if (other.gameReferee2Rank != null)
                return false;
        }
        else if (!this.gameReferee2Rank.equals(other.gameReferee2Rank))
            return false;
        if (this.gameReferee3Rank == null) {
            if (other.gameReferee3Rank != null)
                return false;
        }
        else if (!this.gameReferee3Rank.equals(other.gameReferee3Rank))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.externalId == null) ? 0 : this.externalId.hashCode());
        result = prime * result + ((this.reportType == null) ? 0 : this.reportType.hashCode());
        result = prime * result + ((this.coachId == null) ? 0 : this.coachId.hashCode());
        result = prime * result + ((this.coachName == null) ? 0 : this.coachName.hashCode());
        result = prime * result + ((this.reporteeId == null) ? 0 : this.reporteeId.hashCode());
        result = prime * result + ((this.reporteeName == null) ? 0 : this.reporteeName.hashCode());
        result = prime * result + ((this.reporteeRank == null) ? 0 : this.reporteeRank.hashCode());
        result = prime * result + ((this.gameNumber == null) ? 0 : this.gameNumber.hashCode());
        result = prime * result + ((this.gameCompetition == null) ? 0 : this.gameCompetition.hashCode());
        result = prime * result + ((this.gameDate == null) ? 0 : this.gameDate.hashCode());
        result = prime * result + ((this.gameResult == null) ? 0 : this.gameResult.hashCode());
        result = prime * result + ((this.gameHomeTeam == null) ? 0 : this.gameHomeTeam.hashCode());
        result = prime * result + ((this.gameHomeTeamId == null) ? 0 : this.gameHomeTeamId.hashCode());
        result = prime * result + ((this.gameGuestTeam == null) ? 0 : this.gameGuestTeam.hashCode());
        result = prime * result + ((this.gameGuestTeamId == null) ? 0 : this.gameGuestTeamId.hashCode());
        result = prime * result + ((this.gameReferee1Id == null) ? 0 : this.gameReferee1Id.hashCode());
        result = prime * result + ((this.gameReferee1Name == null) ? 0 : this.gameReferee1Name.hashCode());
        result = prime * result + ((this.gameReferee2Id == null) ? 0 : this.gameReferee2Id.hashCode());
        result = prime * result + ((this.gameReferee2Name == null) ? 0 : this.gameReferee2Name.hashCode());
        result = prime * result + ((this.gameReferee3Id == null) ? 0 : this.gameReferee3Id.hashCode());
        result = prime * result + ((this.gameReferee3Name == null) ? 0 : this.gameReferee3Name.hashCode());
        result = prime * result + ((this.gameVideoUrl == null) ? 0 : this.gameVideoUrl.hashCode());
        result = prime * result + ((this.overallScore == null) ? 0 : this.overallScore.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        result = prime * result + ((this.updatedBy == null) ? 0 : this.updatedBy.hashCode());
        result = prime * result + ((this.finishedAt == null) ? 0 : this.finishedAt.hashCode());
        result = prime * result + ((this.finishedBy == null) ? 0 : this.finishedBy.hashCode());
        result = prime * result + ((this.reminderSent == null) ? 0 : this.reminderSent.hashCode());
        result = prime * result + ((this.gameReferee1Rank == null) ? 0 : this.gameReferee1Rank.hashCode());
        result = prime * result + ((this.gameReferee2Rank == null) ? 0 : this.gameReferee2Rank.hashCode());
        result = prime * result + ((this.gameReferee3Rank == null) ? 0 : this.gameReferee3Rank.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(id);
        sb.append(", ").append(externalId);
        sb.append(", ").append(reportType);
        sb.append(", ").append(coachId);
        sb.append(", ").append(coachName);
        sb.append(", ").append(reporteeId);
        sb.append(", ").append(reporteeName);
        sb.append(", ").append(reporteeRank);
        sb.append(", ").append(gameNumber);
        sb.append(", ").append(gameCompetition);
        sb.append(", ").append(gameDate);
        sb.append(", ").append(gameResult);
        sb.append(", ").append(gameHomeTeam);
        sb.append(", ").append(gameHomeTeamId);
        sb.append(", ").append(gameGuestTeam);
        sb.append(", ").append(gameGuestTeamId);
        sb.append(", ").append(gameReferee1Id);
        sb.append(", ").append(gameReferee1Name);
        sb.append(", ").append(gameReferee2Id);
        sb.append(", ").append(gameReferee2Name);
        sb.append(", ").append(gameReferee3Id);
        sb.append(", ").append(gameReferee3Name);
        sb.append(", ").append(gameVideoUrl);
        sb.append(", ").append(overallScore);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(updatedAt);
        sb.append(", ").append(updatedBy);
        sb.append(", ").append(finishedAt);
        sb.append(", ").append(finishedBy);
        sb.append(", ").append(reminderSent);
        sb.append(", ").append(gameReferee1Rank);
        sb.append(", ").append(gameReferee2Rank);
        sb.append(", ").append(gameReferee3Rank);

        sb.append(")");
        return sb.toString();
    }
}
