/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoUpload implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String objectKey;
    private String filename;
    private String contentType;
    private Long sizeBytes;
    private Boolean uploaded;
    private LocalDateTime createdAt;
    private Long createdBy;

    public ReportVideoUpload() {}

    public ReportVideoUpload(ReportVideoUpload value) {
        this.id = value.id;
        this.objectKey = value.objectKey;
        this.filename = value.filename;
        this.contentType = value.contentType;
        this.sizeBytes = value.sizeBytes;
        this.uploaded = value.uploaded;
        this.createdAt = value.createdAt;
        this.createdBy = value.createdBy;
    }

    public ReportVideoUpload(
        Long id,
        String objectKey,
        String filename,
        String contentType,
        Long sizeBytes,
        Boolean uploaded,
        LocalDateTime createdAt,
        Long createdBy
    ) {
        this.id = id;
        this.objectKey = objectKey;
        this.filename = filename;
        this.contentType = contentType;
        this.sizeBytes = sizeBytes;
        this.uploaded = uploaded;
        this.createdAt = createdAt;
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>public.report_video_upload.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.report_video_upload.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.report_video_upload.object_key</code>.
     */
    public String getObjectKey() {
        return this.objectKey;
    }

    /**
     * Setter for <code>public.report_video_upload.object_key</code>.
     */
    public void setObjectKey(String objectKey) {
        this.objectKey = objectKey;
    }

    /**
     * Getter for <code>public.report_video_upload.filename</code>.
     */
    public String getFilename() {
        return this.filename;
    }

    /**
     * Setter for <code>public.report_video_upload.filename</code>.
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * Getter for <code>public.report_video_upload.content_type</code>.
     */
    public String getContentType() {
        return this.contentType;
    }

    /**
     * Setter for <code>public.report_video_upload.content_type</code>.
     */
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    /**
     * Getter for <code>public.report_video_upload.size_bytes</code>.
     */
    public Long getSizeBytes() {
        return this.sizeBytes;
    }

    /**
     * Setter for <code>public.report_video_upload.size_bytes</code>.
     */
    public void setSizeBytes(Long sizeBytes) {
        this.sizeBytes = sizeBytes;
    }

    /**
     * Getter for <code>public.report_video_upload.uploaded</code>.
     */
    public Boolean getUploaded() {
        return this.uploaded;
    }

    /**
     * Setter for <code>public.report_video_upload.uploaded</code>.
     */
    public void setUploaded(Boolean uploaded) {
        this.uploaded = uploaded;
    }

    /**
     * Getter for <code>public.report_video_upload.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Setter for <code>public.report_video_upload.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for <code>public.report_video_upload.created_by</code>.
     */
    public Long getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>public.report_video_upload.created_by</code>.
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ReportVideoUpload other = (ReportVideoUpload) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.objectKey == null) {
            if (other.objectKey != null)
                return false;
        }
        else if (!this.objectKey.equals(other.objectKey))
            return false;
        if (this.filename == null) {
            if (other.filename != null)
                return false;
        }
        else if (!this.filename.equals(other.filename))
            return false;
        if (this.contentType == null) {
            if (other.contentType != null)
                return false;
        }
        else if (!this.contentType.equals(other.contentType))
            return false;
        if (this.sizeBytes == null) {
            if (other.sizeBytes != null)
                return false;
        }
        else if (!this.sizeBytes.equals(other.sizeBytes))
            return false;
        if (this.uploaded == null) {
            if (other.uploaded != null)
                return false;
        }
        else if (!this.uploaded.equals(other.uploaded))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.objectKey == null) ? 0 : this.objectKey.hashCode());
        result = prime * result + ((this.filename == null) ? 0 : this.filename.hashCode());
        result = prime * result + ((this.contentType == null) ? 0 : this.contentType.hashCode());
        result = prime * result + ((this.sizeBytes == null) ? 0 : this.sizeBytes.hashCode());
        result = prime * result + ((this.uploaded == null) ? 0 : this.uploaded.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ReportVideoUpload (");

        sb.append(id);
        sb.append(", ").append(objectKey);
        sb.append(", ").append(filename);
        sb.append(", ").append(contentType);
        sb.append(", ").append(sizeBytes);
        sb.append(", ").append(uploaded);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(createdBy);

        sb.append(")");
        return sb.toString();
    }
}
