/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportCommentsLastRead;
import ch.refereecoach.probasket.jooq.tables.records.ReportCommentsLastReadRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportCommentsLastReadDao extends AbstractSpringDAOImpl<ReportCommentsLastReadRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead, Record2<Long, Long>> {

    /**
     * Create a new ReportCommentsLastReadDao without any configuration
     */
    public ReportCommentsLastReadDao() {
        super(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ, ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead.class);
    }

    /**
     * Create a new ReportCommentsLastReadDao with an attached configuration
     */
    @Autowired
    public ReportCommentsLastReadDao(Configuration configuration) {
        super(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ, ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead object) {
        return compositeKeyRecord(object.getReportId(), object.getUserId());
    }

    /**
     * Fetch records that have <code>report_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead> fetchRangeOfReportId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ.REPORT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead> fetchByReportId(Long... values) {
        return fetch(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ.REPORT_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead> fetchByUserId(Long... values) {
        return fetch(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ.USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_read_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead> fetchRangeOfLastReadAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ.LAST_READ_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_read_at IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead> fetchByLastReadAt(LocalDateTime... values) {
        return fetch(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ.LAST_READ_AT, values);
    }
}
