/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentReply;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoCommentReplyRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportVideoCommentReplyDao extends AbstractSpringDAOImpl<ReportVideoCommentReplyRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply, Long> {

    /**
     * Create a new ReportVideoCommentReplyDao without any configuration
     */
    public ReportVideoCommentReplyDao() {
        super(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply.class);
    }

    /**
     * Create a new ReportVideoCommentReplyDao with an attached configuration
     */
    @Autowired
    public ReportVideoCommentReplyDao(Configuration configuration) {
        super(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply.class, configuration);
    }

    @Override
    public Long getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchById(Long... values) {
        return fetch(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply fetchOneById(Long value) {
        return fetchOne(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchOptionalById(Long value) {
        return fetchOptional(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.ID, value);
    }

    /**
     * Fetch records that have <code>report_video_comment_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchRangeOfReportVideoCommentId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.REPORT_VIDEO_COMMENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_video_comment_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchByReportVideoCommentId(Long... values) {
        return fetch(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.REPORT_VIDEO_COMMENT_ID, values);
    }

    /**
     * Fetch records that have <code>reply BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchRangeOfReply(String lowerInclusive, String upperInclusive) {
        return fetchRange(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.REPLY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>reply IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchByReply(String... values) {
        return fetch(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.REPLY, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply> fetchByCreatedBy(Long... values) {
        return fetch(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY.CREATED_BY, values);
    }
}
