/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportLastRead;
import ch.refereecoach.probasket.jooq.tables.records.ReportLastReadRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportLastReadDao extends AbstractSpringDAOImpl<ReportLastReadRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead, Record2<Long, Long>> {

    /**
     * Create a new ReportLastReadDao without any configuration
     */
    public ReportLastReadDao() {
        super(ReportLastRead.REPORT_LAST_READ, ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead.class);
    }

    /**
     * Create a new ReportLastReadDao with an attached configuration
     */
    @Autowired
    public ReportLastReadDao(Configuration configuration) {
        super(ReportLastRead.REPORT_LAST_READ, ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead object) {
        return compositeKeyRecord(object.getReportId(), object.getUserId());
    }

    /**
     * Fetch records that have <code>report_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead> fetchRangeOfReportId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportLastRead.REPORT_LAST_READ.REPORT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead> fetchByReportId(Long... values) {
        return fetch(ReportLastRead.REPORT_LAST_READ.REPORT_ID, values);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead> fetchRangeOfUserId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportLastRead.REPORT_LAST_READ.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead> fetchByUserId(Long... values) {
        return fetch(ReportLastRead.REPORT_LAST_READ.USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_read_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead> fetchRangeOfLastReadAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ReportLastRead.REPORT_LAST_READ.LAST_READ_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_read_at IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportLastRead> fetchByLastReadAt(LocalDateTime... values) {
        return fetch(ReportLastRead.REPORT_LAST_READ.LAST_READ_AT, values);
    }
}
