/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportVideoUpload;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoUploadRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportVideoUploadDao extends AbstractSpringDAOImpl<ReportVideoUploadRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload, Long> {

    /**
     * Create a new ReportVideoUploadDao without any configuration
     */
    public ReportVideoUploadDao() {
        super(ReportVideoUpload.REPORT_VIDEO_UPLOAD, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload.class);
    }

    /**
     * Create a new ReportVideoUploadDao with an attached configuration
     */
    @Autowired
    public ReportVideoUploadDao(Configuration configuration) {
        super(ReportVideoUpload.REPORT_VIDEO_UPLOAD, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload.class, configuration);
    }

    @Override
    public Long getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchById(Long... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload fetchOneById(Long value) {
        return fetchOne(ReportVideoUpload.REPORT_VIDEO_UPLOAD.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchOptionalById(Long value) {
        return fetchOptional(ReportVideoUpload.REPORT_VIDEO_UPLOAD.ID, value);
    }

    /**
     * Fetch records that have <code>object_key BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfObjectKey(String lowerInclusive, String upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.OBJECT_KEY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>object_key IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchByObjectKey(String... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.OBJECT_KEY, values);
    }

    /**
     * Fetch records that have <code>filename BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfFilename(String lowerInclusive, String upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.FILENAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>filename IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchByFilename(String... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.FILENAME, values);
    }

    /**
     * Fetch records that have <code>content_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfContentType(String lowerInclusive, String upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.CONTENT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>content_type IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchByContentType(String... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.CONTENT_TYPE, values);
    }

    /**
     * Fetch records that have <code>size_bytes BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfSizeBytes(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.SIZE_BYTES, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>size_bytes IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchBySizeBytes(Long... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.SIZE_BYTES, values);
    }

    /**
     * Fetch records that have <code>uploaded BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfUploaded(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.UPLOADED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>uploaded IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchByUploaded(Boolean... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.UPLOADED, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoUpload.REPORT_VIDEO_UPLOAD.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload> fetchByCreatedBy(Long... values) {
        return fetch(ReportVideoUpload.REPORT_VIDEO_UPLOAD.CREATED_BY, values);
    }
}
