/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportVideoComment;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoCommentRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportVideoCommentDao extends AbstractSpringDAOImpl<ReportVideoCommentRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment, Long> {

    /**
     * Create a new ReportVideoCommentDao without any configuration
     */
    public ReportVideoCommentDao() {
        super(ReportVideoComment.REPORT_VIDEO_COMMENT, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment.class);
    }

    /**
     * Create a new ReportVideoCommentDao with an attached configuration
     */
    @Autowired
    public ReportVideoCommentDao(Configuration configuration) {
        super(ReportVideoComment.REPORT_VIDEO_COMMENT, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment.class, configuration);
    }

    @Override
    public Long getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchById(Long... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment fetchOneById(Long value) {
        return fetchOne(ReportVideoComment.REPORT_VIDEO_COMMENT.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchOptionalById(Long value) {
        return fetchOptional(ReportVideoComment.REPORT_VIDEO_COMMENT.ID, value);
    }

    /**
     * Fetch records that have <code>report_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfReportId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.REPORT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchByReportId(Long... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.REPORT_ID, values);
    }

    /**
     * Fetch records that have <code>timestamp_in_seconds BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfTimestampInSeconds(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.TIMESTAMP_IN_SECONDS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>timestamp_in_seconds IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchByTimestampInSeconds(Long... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.TIMESTAMP_IN_SECONDS, values);
    }

    /**
     * Fetch records that have <code>comment BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfComment(String lowerInclusive, String upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.COMMENT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>comment IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchByComment(String... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.COMMENT, values);
    }

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfCreatedAt(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.CREATED_AT, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchByCreatedAt(LocalDateTime... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.CREATED_AT, values);
    }

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfCreatedBy(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.CREATED_BY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchByCreatedBy(Long... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.CREATED_BY, values);
    }

    /**
     * Fetch records that have <code>requires_reply BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchRangeOfRequiresReply(Boolean lowerInclusive, Boolean upperInclusive) {
        return fetchRange(ReportVideoComment.REPORT_VIDEO_COMMENT.REQUIRES_REPLY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>requires_reply IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoComment> fetchByRequiresReply(Boolean... values) {
        return fetch(ReportVideoComment.REPORT_VIDEO_COMMENT.REQUIRES_REPLY, values);
    }
}
