/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentTag;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoCommentTagRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportVideoCommentTagDao extends AbstractSpringDAOImpl<ReportVideoCommentTagRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag, Record2<Long, Long>> {

    /**
     * Create a new ReportVideoCommentTagDao without any configuration
     */
    public ReportVideoCommentTagDao() {
        super(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag.class);
    }

    /**
     * Create a new ReportVideoCommentTagDao with an attached configuration
     */
    @Autowired
    public ReportVideoCommentTagDao(Configuration configuration) {
        super(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag object) {
        return compositeKeyRecord(object.getReportVideoCommentId(), object.getTagId());
    }

    /**
     * Fetch records that have <code>report_video_comment_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag> fetchRangeOfReportVideoCommentId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG.REPORT_VIDEO_COMMENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_video_comment_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag> fetchByReportVideoCommentId(Long... values) {
        return fetch(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG.REPORT_VIDEO_COMMENT_ID, values);
    }

    /**
     * Fetch records that have <code>tag_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag> fetchRangeOfTagId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG.TAG_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>tag_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag> fetchByTagId(Long... values) {
        return fetch(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG.TAG_ID, values);
    }
}
