/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.daos;


import ch.refereecoach.probasket.jooq.AbstractSpringDAOImpl;
import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentRef;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoCommentRefRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
@Repository
public class ReportVideoCommentRefDao extends AbstractSpringDAOImpl<ReportVideoCommentRefRecord, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef, Record2<Long, Long>> {

    /**
     * Create a new ReportVideoCommentRefDao without any configuration
     */
    public ReportVideoCommentRefDao() {
        super(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef.class);
    }

    /**
     * Create a new ReportVideoCommentRefDao with an attached configuration
     */
    @Autowired
    public ReportVideoCommentRefDao(Configuration configuration) {
        super(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF, ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef object) {
        return compositeKeyRecord(object.getReportId(), object.getReportVideoCommentId());
    }

    /**
     * Fetch records that have <code>report_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef> fetchRangeOfReportId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF.REPORT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef> fetchByReportId(Long... values) {
        return fetch(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF.REPORT_ID, values);
    }

    /**
     * Fetch records that have <code>report_video_comment_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef> fetchRangeOfReportVideoCommentId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF.REPORT_VIDEO_COMMENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>report_video_comment_id IN (values)</code>
     */
    public List<ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef> fetchByReportVideoCommentId(Long... values) {
        return fetch(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF.REPORT_VIDEO_COMMENT_ID, values);
    }
}
