/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq;


import ch.refereecoach.probasket.jooq.tables.Login;
import ch.refereecoach.probasket.jooq.tables.Tags;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.login</code>.
     */
    public final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>public.tags</code>.
     */
    public final Tags TAGS = Tags.TAGS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Login.LOGIN,
            Tags.TAGS
        );
    }
}
