/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq;


import ch.refereecoach.probasket.jooq.tables.Login;
import ch.refereecoach.probasket.jooq.tables.Report;
import ch.refereecoach.probasket.jooq.tables.ReportComment;
import ch.refereecoach.probasket.jooq.tables.ReportCriteria;
import ch.refereecoach.probasket.jooq.tables.ReportLastRead;
import ch.refereecoach.probasket.jooq.tables.ReportVideoComment;
import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentReply;
import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentTag;
import ch.refereecoach.probasket.jooq.tables.Tag;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.login</code>.
     */
    public final Login LOGIN = Login.LOGIN;

    /**
     * The table <code>public.report</code>.
     */
    public final Report REPORT = Report.REPORT;

    /**
     * The table <code>public.report_comment</code>.
     */
    public final ReportComment REPORT_COMMENT = ReportComment.REPORT_COMMENT;

    /**
     * The table <code>public.report_criteria</code>.
     */
    public final ReportCriteria REPORT_CRITERIA = ReportCriteria.REPORT_CRITERIA;

    /**
     * The table <code>public.report_last_read</code>.
     */
    public final ReportLastRead REPORT_LAST_READ = ReportLastRead.REPORT_LAST_READ;

    /**
     * The table <code>public.report_video_comment</code>.
     */
    public final ReportVideoComment REPORT_VIDEO_COMMENT = ReportVideoComment.REPORT_VIDEO_COMMENT;

    /**
     * The table <code>public.report_video_comment_reply</code>.
     */
    public final ReportVideoCommentReply REPORT_VIDEO_COMMENT_REPLY = ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY;

    /**
     * The table <code>public.report_video_comment_tag</code>.
     */
    public final ReportVideoCommentTag REPORT_VIDEO_COMMENT_TAG = ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG;

    /**
     * The table <code>public.tag</code>.
     */
    public final Tag TAG = Tag.TAG;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Login.LOGIN,
            Report.REPORT,
            ReportComment.REPORT_COMMENT,
            ReportCriteria.REPORT_CRITERIA,
            ReportLastRead.REPORT_LAST_READ,
            ReportVideoComment.REPORT_VIDEO_COMMENT,
            ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY,
            ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG,
            Tag.TAG
        );
    }
}
