/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq;


import org.jooq.Sequence;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * Convenience access to all sequences in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Sequences {

    /**
     * The sequence <code>public.login_local_id_seq</code>
     */
    public static final Sequence<Long> LOGIN_LOCAL_ID_SEQ = Internal.createSequence("login_local_id_seq", Public.PUBLIC, DSL.comment(""), SQLDataType.BIGINT.nullable(false), 1000000000, null, null, null, false, null);
}
