/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables;


import ch.refereecoach.probasket.jooq.Keys;
import ch.refereecoach.probasket.jooq.Public;
import ch.refereecoach.probasket.jooq.tables.Login.LoginPath;
import ch.refereecoach.probasket.jooq.tables.ReportVideoComment.ReportVideoCommentPath;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoUploadRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoUpload extends TableImpl<ReportVideoUploadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report_video_upload</code>
     */
    public static final ReportVideoUpload REPORT_VIDEO_UPLOAD = new ReportVideoUpload();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVideoUploadRecord> getRecordType() {
        return ReportVideoUploadRecord.class;
    }

    /**
     * The column <code>public.report_video_upload.id</code>.
     */
    public final TableField<ReportVideoUploadRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.report_video_upload.object_key</code>.
     */
    public final TableField<ReportVideoUploadRecord, String> OBJECT_KEY = createField(DSL.name("object_key"), SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * The column <code>public.report_video_upload.filename</code>.
     */
    public final TableField<ReportVideoUploadRecord, String> FILENAME = createField(DSL.name("filename"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.report_video_upload.content_type</code>.
     */
    public final TableField<ReportVideoUploadRecord, String> CONTENT_TYPE = createField(DSL.name("content_type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.report_video_upload.size_bytes</code>.
     */
    public final TableField<ReportVideoUploadRecord, Long> SIZE_BYTES = createField(DSL.name("size_bytes"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.report_video_upload.uploaded</code>.
     */
    public final TableField<ReportVideoUploadRecord, Boolean> UPLOADED = createField(DSL.name("uploaded"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.report_video_upload.created_at</code>.
     */
    public final TableField<ReportVideoUploadRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.report_video_upload.created_by</code>.
     */
    public final TableField<ReportVideoUploadRecord, Long> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "");

    private ReportVideoUpload(Name alias, Table<ReportVideoUploadRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReportVideoUpload(Name alias, Table<ReportVideoUploadRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report_video_upload</code> table reference
     */
    public ReportVideoUpload(String alias) {
        this(DSL.name(alias), REPORT_VIDEO_UPLOAD);
    }

    /**
     * Create an aliased <code>public.report_video_upload</code> table reference
     */
    public ReportVideoUpload(Name alias) {
        this(alias, REPORT_VIDEO_UPLOAD);
    }

    /**
     * Create a <code>public.report_video_upload</code> table reference
     */
    public ReportVideoUpload() {
        this(DSL.name("report_video_upload"), null);
    }

    public <O extends Record> ReportVideoUpload(Table<O> path, ForeignKey<O, ReportVideoUploadRecord> childPath, InverseForeignKey<O, ReportVideoUploadRecord> parentPath) {
        super(path, childPath, parentPath, REPORT_VIDEO_UPLOAD);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReportVideoUploadPath extends ReportVideoUpload implements Path<ReportVideoUploadRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReportVideoUploadPath(Table<O> path, ForeignKey<O, ReportVideoUploadRecord> childPath, InverseForeignKey<O, ReportVideoUploadRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReportVideoUploadPath(Name alias, Table<ReportVideoUploadRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReportVideoUploadPath as(String alias) {
            return new ReportVideoUploadPath(DSL.name(alias), this);
        }

        @Override
        public ReportVideoUploadPath as(Name alias) {
            return new ReportVideoUploadPath(alias, this);
        }

        @Override
        public ReportVideoUploadPath as(Table<?> alias) {
            return new ReportVideoUploadPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ReportVideoUploadRecord> getPrimaryKey() {
        return Keys.PK__REPORT_VIDEO_UPLOAD;
    }

    @Override
    public List<ForeignKey<ReportVideoUploadRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORT_VIDEO_UPLOAD__FK__REPORT_VIDEO_UPLOAD_CREATED_BY);
    }

    private transient LoginPath _login;

    /**
     * Get the implicit join path to the <code>public.login</code> table.
     */
    public LoginPath login() {
        if (_login == null)
            _login = new LoginPath(this, Keys.REPORT_VIDEO_UPLOAD__FK__REPORT_VIDEO_UPLOAD_CREATED_BY, null);

        return _login;
    }

    private transient ReportVideoCommentPath _reportVideoComment;

    /**
     * Get the implicit to-many join path to the
     * <code>public.report_video_comment</code> table
     */
    public ReportVideoCommentPath reportVideoComment() {
        if (_reportVideoComment == null)
            _reportVideoComment = new ReportVideoCommentPath(this, null, Keys.REPORT_VIDEO_COMMENT__FK__REPORT_VIDEO_COMMENT_UPLOAD.getInverseKey());

        return _reportVideoComment;
    }

    @Override
    public ReportVideoUpload as(String alias) {
        return new ReportVideoUpload(DSL.name(alias), this);
    }

    @Override
    public ReportVideoUpload as(Name alias) {
        return new ReportVideoUpload(alias, this);
    }

    @Override
    public ReportVideoUpload as(Table<?> alias) {
        return new ReportVideoUpload(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoUpload rename(String name) {
        return new ReportVideoUpload(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoUpload rename(Name name) {
        return new ReportVideoUpload(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoUpload rename(Table<?> name) {
        return new ReportVideoUpload(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoUpload where(Condition condition) {
        return new ReportVideoUpload(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoUpload where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoUpload where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoUpload where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoUpload where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoUpload where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoUpload where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoUpload where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoUpload whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoUpload whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
