/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables;


import ch.refereecoach.probasket.jooq.Keys;
import ch.refereecoach.probasket.jooq.Public;
import ch.refereecoach.probasket.jooq.tables.Report.ReportPath;
import ch.refereecoach.probasket.jooq.tables.records.ReportCriteriaRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportCriteria extends TableImpl<ReportCriteriaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report_criteria</code>
     */
    public static final ReportCriteria REPORT_CRITERIA = new ReportCriteria();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportCriteriaRecord> getRecordType() {
        return ReportCriteriaRecord.class;
    }

    /**
     * The column <code>public.report_criteria.id</code>.
     */
    public final TableField<ReportCriteriaRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.report_criteria.report_id</code>.
     */
    public final TableField<ReportCriteriaRecord, Long> REPORT_ID = createField(DSL.name("report_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.report_criteria.type</code>.
     */
    public final TableField<ReportCriteriaRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.report_criteria.comment</code>.
     */
    public final TableField<ReportCriteriaRecord, String> COMMENT = createField(DSL.name("comment"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.report_criteria.state</code>.
     */
    public final TableField<ReportCriteriaRecord, String> STATE = createField(DSL.name("state"), SQLDataType.VARCHAR(255), this, "");

    private ReportCriteria(Name alias, Table<ReportCriteriaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReportCriteria(Name alias, Table<ReportCriteriaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report_criteria</code> table reference
     */
    public ReportCriteria(String alias) {
        this(DSL.name(alias), REPORT_CRITERIA);
    }

    /**
     * Create an aliased <code>public.report_criteria</code> table reference
     */
    public ReportCriteria(Name alias) {
        this(alias, REPORT_CRITERIA);
    }

    /**
     * Create a <code>public.report_criteria</code> table reference
     */
    public ReportCriteria() {
        this(DSL.name("report_criteria"), null);
    }

    public <O extends Record> ReportCriteria(Table<O> path, ForeignKey<O, ReportCriteriaRecord> childPath, InverseForeignKey<O, ReportCriteriaRecord> parentPath) {
        super(path, childPath, parentPath, REPORT_CRITERIA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReportCriteriaPath extends ReportCriteria implements Path<ReportCriteriaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReportCriteriaPath(Table<O> path, ForeignKey<O, ReportCriteriaRecord> childPath, InverseForeignKey<O, ReportCriteriaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReportCriteriaPath(Name alias, Table<ReportCriteriaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReportCriteriaPath as(String alias) {
            return new ReportCriteriaPath(DSL.name(alias), this);
        }

        @Override
        public ReportCriteriaPath as(Name alias) {
            return new ReportCriteriaPath(alias, this);
        }

        @Override
        public ReportCriteriaPath as(Table<?> alias) {
            return new ReportCriteriaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<ReportCriteriaRecord, Long> getIdentity() {
        return (Identity<ReportCriteriaRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<ReportCriteriaRecord> getPrimaryKey() {
        return Keys.PK__REPORT_CRITERIA;
    }

    @Override
    public List<ForeignKey<ReportCriteriaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORT_CRITERIA__FK__REPORT_CRITERIA_REPORT);
    }

    private transient ReportPath _report;

    /**
     * Get the implicit join path to the <code>public.report</code> table.
     */
    public ReportPath report() {
        if (_report == null)
            _report = new ReportPath(this, Keys.REPORT_CRITERIA__FK__REPORT_CRITERIA_REPORT, null);

        return _report;
    }

    @Override
    public ReportCriteria as(String alias) {
        return new ReportCriteria(DSL.name(alias), this);
    }

    @Override
    public ReportCriteria as(Name alias) {
        return new ReportCriteria(alias, this);
    }

    @Override
    public ReportCriteria as(Table<?> alias) {
        return new ReportCriteria(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportCriteria rename(String name) {
        return new ReportCriteria(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportCriteria rename(Name name) {
        return new ReportCriteria(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportCriteria rename(Table<?> name) {
        return new ReportCriteria(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportCriteria where(Condition condition) {
        return new ReportCriteria(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportCriteria where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportCriteria where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportCriteria where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportCriteria where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportCriteria where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportCriteria where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportCriteria where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportCriteria whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportCriteria whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
