/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables;


import ch.refereecoach.probasket.jooq.Keys;
import ch.refereecoach.probasket.jooq.Public;
import ch.refereecoach.probasket.jooq.tables.ReportVideoComment.ReportVideoCommentPath;
import ch.refereecoach.probasket.jooq.tables.Tag.TagPath;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoCommentTagRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentTag extends TableImpl<ReportVideoCommentTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report_video_comment_tag</code>
     */
    public static final ReportVideoCommentTag REPORT_VIDEO_COMMENT_TAG = new ReportVideoCommentTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVideoCommentTagRecord> getRecordType() {
        return ReportVideoCommentTagRecord.class;
    }

    /**
     * The column
     * <code>public.report_video_comment_tag.report_video_comment_id</code>.
     */
    public final TableField<ReportVideoCommentTagRecord, Long> REPORT_VIDEO_COMMENT_ID = createField(DSL.name("report_video_comment_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.report_video_comment_tag.tag_id</code>.
     */
    public final TableField<ReportVideoCommentTagRecord, Long> TAG_ID = createField(DSL.name("tag_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private ReportVideoCommentTag(Name alias, Table<ReportVideoCommentTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReportVideoCommentTag(Name alias, Table<ReportVideoCommentTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report_video_comment_tag</code> table
     * reference
     */
    public ReportVideoCommentTag(String alias) {
        this(DSL.name(alias), REPORT_VIDEO_COMMENT_TAG);
    }

    /**
     * Create an aliased <code>public.report_video_comment_tag</code> table
     * reference
     */
    public ReportVideoCommentTag(Name alias) {
        this(alias, REPORT_VIDEO_COMMENT_TAG);
    }

    /**
     * Create a <code>public.report_video_comment_tag</code> table reference
     */
    public ReportVideoCommentTag() {
        this(DSL.name("report_video_comment_tag"), null);
    }

    public <O extends Record> ReportVideoCommentTag(Table<O> path, ForeignKey<O, ReportVideoCommentTagRecord> childPath, InverseForeignKey<O, ReportVideoCommentTagRecord> parentPath) {
        super(path, childPath, parentPath, REPORT_VIDEO_COMMENT_TAG);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReportVideoCommentTagPath extends ReportVideoCommentTag implements Path<ReportVideoCommentTagRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReportVideoCommentTagPath(Table<O> path, ForeignKey<O, ReportVideoCommentTagRecord> childPath, InverseForeignKey<O, ReportVideoCommentTagRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReportVideoCommentTagPath(Name alias, Table<ReportVideoCommentTagRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReportVideoCommentTagPath as(String alias) {
            return new ReportVideoCommentTagPath(DSL.name(alias), this);
        }

        @Override
        public ReportVideoCommentTagPath as(Name alias) {
            return new ReportVideoCommentTagPath(alias, this);
        }

        @Override
        public ReportVideoCommentTagPath as(Table<?> alias) {
            return new ReportVideoCommentTagPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ReportVideoCommentTagRecord> getPrimaryKey() {
        return Keys.PK__REPORT_VIDEO_COMMENT_TAG;
    }

    @Override
    public List<ForeignKey<ReportVideoCommentTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORT_VIDEO_COMMENT_TAG__FK__REPORT_VIDEO_COMMENT_TAG_COMMENT, Keys.REPORT_VIDEO_COMMENT_TAG__FK__REPORT_VIDEO_COMMENT_TAG_TAG);
    }

    private transient ReportVideoCommentPath _reportVideoComment;

    /**
     * Get the implicit join path to the
     * <code>public.report_video_comment</code> table.
     */
    public ReportVideoCommentPath reportVideoComment() {
        if (_reportVideoComment == null)
            _reportVideoComment = new ReportVideoCommentPath(this, Keys.REPORT_VIDEO_COMMENT_TAG__FK__REPORT_VIDEO_COMMENT_TAG_COMMENT, null);

        return _reportVideoComment;
    }

    private transient TagPath _tag;

    /**
     * Get the implicit join path to the <code>public.tag</code> table.
     */
    public TagPath tag() {
        if (_tag == null)
            _tag = new TagPath(this, Keys.REPORT_VIDEO_COMMENT_TAG__FK__REPORT_VIDEO_COMMENT_TAG_TAG, null);

        return _tag;
    }

    @Override
    public ReportVideoCommentTag as(String alias) {
        return new ReportVideoCommentTag(DSL.name(alias), this);
    }

    @Override
    public ReportVideoCommentTag as(Name alias) {
        return new ReportVideoCommentTag(alias, this);
    }

    @Override
    public ReportVideoCommentTag as(Table<?> alias) {
        return new ReportVideoCommentTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoCommentTag rename(String name) {
        return new ReportVideoCommentTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoCommentTag rename(Name name) {
        return new ReportVideoCommentTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoCommentTag rename(Table<?> name) {
        return new ReportVideoCommentTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentTag where(Condition condition) {
        return new ReportVideoCommentTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
