/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables;


import ch.refereecoach.probasket.jooq.Keys;
import ch.refereecoach.probasket.jooq.Public;
import ch.refereecoach.probasket.jooq.tables.Report.ReportPath;
import ch.refereecoach.probasket.jooq.tables.ReportVideoComment.ReportVideoCommentPath;
import ch.refereecoach.probasket.jooq.tables.records.ReportVideoCommentRefRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentRef extends TableImpl<ReportVideoCommentRefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.report_video_comment_ref</code>
     */
    public static final ReportVideoCommentRef REPORT_VIDEO_COMMENT_REF = new ReportVideoCommentRef();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReportVideoCommentRefRecord> getRecordType() {
        return ReportVideoCommentRefRecord.class;
    }

    /**
     * The column <code>public.report_video_comment_ref.report_id</code>.
     */
    public final TableField<ReportVideoCommentRefRecord, Long> REPORT_ID = createField(DSL.name("report_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>public.report_video_comment_ref.report_video_comment_id</code>.
     */
    public final TableField<ReportVideoCommentRefRecord, Long> REPORT_VIDEO_COMMENT_ID = createField(DSL.name("report_video_comment_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.report_video_comment_ref.requires_reply</code>.
     */
    public final TableField<ReportVideoCommentRefRecord, Boolean> REQUIRES_REPLY = createField(DSL.name("requires_reply"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private ReportVideoCommentRef(Name alias, Table<ReportVideoCommentRefRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ReportVideoCommentRef(Name alias, Table<ReportVideoCommentRefRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.report_video_comment_ref</code> table
     * reference
     */
    public ReportVideoCommentRef(String alias) {
        this(DSL.name(alias), REPORT_VIDEO_COMMENT_REF);
    }

    /**
     * Create an aliased <code>public.report_video_comment_ref</code> table
     * reference
     */
    public ReportVideoCommentRef(Name alias) {
        this(alias, REPORT_VIDEO_COMMENT_REF);
    }

    /**
     * Create a <code>public.report_video_comment_ref</code> table reference
     */
    public ReportVideoCommentRef() {
        this(DSL.name("report_video_comment_ref"), null);
    }

    public <O extends Record> ReportVideoCommentRef(Table<O> path, ForeignKey<O, ReportVideoCommentRefRecord> childPath, InverseForeignKey<O, ReportVideoCommentRefRecord> parentPath) {
        super(path, childPath, parentPath, REPORT_VIDEO_COMMENT_REF);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ReportVideoCommentRefPath extends ReportVideoCommentRef implements Path<ReportVideoCommentRefRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ReportVideoCommentRefPath(Table<O> path, ForeignKey<O, ReportVideoCommentRefRecord> childPath, InverseForeignKey<O, ReportVideoCommentRefRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ReportVideoCommentRefPath(Name alias, Table<ReportVideoCommentRefRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ReportVideoCommentRefPath as(String alias) {
            return new ReportVideoCommentRefPath(DSL.name(alias), this);
        }

        @Override
        public ReportVideoCommentRefPath as(Name alias) {
            return new ReportVideoCommentRefPath(alias, this);
        }

        @Override
        public ReportVideoCommentRefPath as(Table<?> alias) {
            return new ReportVideoCommentRefPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ReportVideoCommentRefRecord> getPrimaryKey() {
        return Keys.PK__REPORT_VIDEO_COMMENT_REF;
    }

    @Override
    public List<ForeignKey<ReportVideoCommentRefRecord, ?>> getReferences() {
        return Arrays.asList(Keys.REPORT_VIDEO_COMMENT_REF__FK__REPORT_COACH, Keys.REPORT_VIDEO_COMMENT_REF__FK__REPORT_REPORTEE);
    }

    private transient ReportPath _report;

    /**
     * Get the implicit join path to the <code>public.report</code> table.
     */
    public ReportPath report() {
        if (_report == null)
            _report = new ReportPath(this, Keys.REPORT_VIDEO_COMMENT_REF__FK__REPORT_COACH, null);

        return _report;
    }

    private transient ReportVideoCommentPath _reportVideoComment;

    /**
     * Get the implicit join path to the
     * <code>public.report_video_comment</code> table.
     */
    public ReportVideoCommentPath reportVideoComment() {
        if (_reportVideoComment == null)
            _reportVideoComment = new ReportVideoCommentPath(this, Keys.REPORT_VIDEO_COMMENT_REF__FK__REPORT_REPORTEE, null);

        return _reportVideoComment;
    }

    @Override
    public ReportVideoCommentRef as(String alias) {
        return new ReportVideoCommentRef(DSL.name(alias), this);
    }

    @Override
    public ReportVideoCommentRef as(Name alias) {
        return new ReportVideoCommentRef(alias, this);
    }

    @Override
    public ReportVideoCommentRef as(Table<?> alias) {
        return new ReportVideoCommentRef(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoCommentRef rename(String name) {
        return new ReportVideoCommentRef(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoCommentRef rename(Name name) {
        return new ReportVideoCommentRef(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ReportVideoCommentRef rename(Table<?> name) {
        return new ReportVideoCommentRef(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentRef where(Condition condition) {
        return new ReportVideoCommentRef(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentRef where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentRef where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentRef where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentRef where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentRef where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentRef where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ReportVideoCommentRef where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentRef whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ReportVideoCommentRef whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
