/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.Login;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LoginRecord extends UpdatableRecordImpl<LoginRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.login.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.login.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.login.firstname</code>.
     */
    public void setFirstname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.login.firstname</code>.
     */
    public String getFirstname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.login.lastname</code>.
     */
    public void setLastname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.login.lastname</code>.
     */
    public String getLastname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.login.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.login.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.login.last_login</code>.
     */
    public void setLastLogin(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.login.last_login</code>.
     */
    public LocalDateTime getLastLogin() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.login.referee_coach</code>.
     */
    public void setRefereeCoach(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.login.referee_coach</code>.
     */
    public Boolean getRefereeCoach() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.login.referee</code>.
     */
    public void setReferee(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.login.referee</code>.
     */
    public Boolean getReferee() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.login.trainer_coach</code>.
     */
    public void setTrainerCoach(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.login.trainer_coach</code>.
     */
    public Boolean getTrainerCoach() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.login.trainer</code>.
     */
    public void setTrainer(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.login.trainer</code>.
     */
    public Boolean getTrainer() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.login.admin</code>.
     */
    public void setAdmin(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.login.admin</code>.
     */
    public Boolean getAdmin() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.login.rank</code>.
     */
    public void setRank(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.login.rank</code>.
     */
    public String getRank() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.login.active</code>.
     */
    public void setActive(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.login.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.login.referee_coach_plus</code>.
     */
    public void setRefereeCoachPlus(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.login.referee_coach_plus</code>.
     */
    public Boolean getRefereeCoachPlus() {
        return (Boolean) get(12);
    }

    /**
     * Setter for <code>public.login.username</code>.
     */
    public void setUsername(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.login.username</code>.
     */
    public String getUsername() {
        return (String) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LoginRecord
     */
    public LoginRecord() {
        super(Login.LOGIN);
    }

    /**
     * Create a detached, initialised LoginRecord
     */
    public LoginRecord(Long id, String firstname, String lastname, String email, LocalDateTime lastLogin, Boolean refereeCoach, Boolean referee, Boolean trainerCoach, Boolean trainer, Boolean admin, String rank, Boolean active, Boolean refereeCoachPlus, String username) {
        super(Login.LOGIN);

        setId(id);
        setFirstname(firstname);
        setLastname(lastname);
        setEmail(email);
        setLastLogin(lastLogin);
        setRefereeCoach(refereeCoach);
        setReferee(referee);
        setTrainerCoach(trainerCoach);
        setTrainer(trainer);
        setAdmin(admin);
        setRank(rank);
        setActive(active);
        setRefereeCoachPlus(refereeCoachPlus);
        setUsername(username);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised LoginRecord
     */
    public LoginRecord(ch.refereecoach.probasket.jooq.tables.pojos.Login value) {
        super(Login.LOGIN);

        if (value != null) {
            setId(value.getId());
            setFirstname(value.getFirstname());
            setLastname(value.getLastname());
            setEmail(value.getEmail());
            setLastLogin(value.getLastLogin());
            setRefereeCoach(value.getRefereeCoach());
            setReferee(value.getReferee());
            setTrainerCoach(value.getTrainerCoach());
            setTrainer(value.getTrainer());
            setAdmin(value.getAdmin());
            setRank(value.getRank());
            setActive(value.getActive());
            setRefereeCoachPlus(value.getRefereeCoachPlus());
            setUsername(value.getUsername());
            resetChangedOnNotNull();
        }
    }
}
