/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentRef;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentRefRecord extends UpdatableRecordImpl<ReportVideoCommentRefRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_video_comment_ref.report_id</code>.
     */
    public void setReportId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_video_comment_ref.report_id</code>.
     */
    public Long getReportId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.report_video_comment_ref.report_video_comment_id</code>.
     */
    public void setReportVideoCommentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.report_video_comment_ref.report_video_comment_id</code>.
     */
    public Long getReportVideoCommentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.report_video_comment_ref.requires_reply</code>.
     */
    public void setRequiresReply(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_video_comment_ref.requires_reply</code>.
     */
    public Boolean getRequiresReply() {
        return (Boolean) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVideoCommentRefRecord
     */
    public ReportVideoCommentRefRecord() {
        super(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF);
    }

    /**
     * Create a detached, initialised ReportVideoCommentRefRecord
     */
    public ReportVideoCommentRefRecord(Long reportId, Long reportVideoCommentId, Boolean requiresReply) {
        super(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF);

        setReportId(reportId);
        setReportVideoCommentId(reportVideoCommentId);
        setRequiresReply(requiresReply);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportVideoCommentRefRecord
     */
    public ReportVideoCommentRefRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentRef value) {
        super(ReportVideoCommentRef.REPORT_VIDEO_COMMENT_REF);

        if (value != null) {
            setReportId(value.getReportId());
            setReportVideoCommentId(value.getReportVideoCommentId());
            setRequiresReply(value.getRequiresReply());
            resetChangedOnNotNull();
        }
    }
}
