/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.Report;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportRecord extends UpdatableRecordImpl<ReportRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.report.external_id</code>.
     */
    public void setExternalId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report.external_id</code>.
     */
    public String getExternalId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.report.report_type</code>.
     */
    public void setReportType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report.report_type</code>.
     */
    public String getReportType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.report.coach_id</code>.
     */
    public void setCoachId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.report.coach_id</code>.
     */
    public Long getCoachId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.report.coach_name</code>.
     */
    public void setCoachName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.report.coach_name</code>.
     */
    public String getCoachName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.report.reportee_id</code>.
     */
    public void setReporteeId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.report.reportee_id</code>.
     */
    public Long getReporteeId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.report.reportee_name</code>.
     */
    public void setReporteeName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.report.reportee_name</code>.
     */
    public String getReporteeName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.report.game_number</code>.
     */
    public void setGameNumber(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.report.game_number</code>.
     */
    public String getGameNumber() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.report.game_competition</code>.
     */
    public void setGameCompetition(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.report.game_competition</code>.
     */
    public String getGameCompetition() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.report.game_date</code>.
     */
    public void setGameDate(LocalDate value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.report.game_date</code>.
     */
    public LocalDate getGameDate() {
        return (LocalDate) get(9);
    }

    /**
     * Setter for <code>public.report.game_result</code>.
     */
    public void setGameResult(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.report.game_result</code>.
     */
    public String getGameResult() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.report.game_home_team</code>.
     */
    public void setGameHomeTeam(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.report.game_home_team</code>.
     */
    public String getGameHomeTeam() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.report.game_home_team_id</code>.
     */
    public void setGameHomeTeamId(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.report.game_home_team_id</code>.
     */
    public Integer getGameHomeTeamId() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.report.game_guest_team</code>.
     */
    public void setGameGuestTeam(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.report.game_guest_team</code>.
     */
    public String getGameGuestTeam() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.report.game_guest_team_id</code>.
     */
    public void setGameGuestTeamId(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.report.game_guest_team_id</code>.
     */
    public Integer getGameGuestTeamId() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.report.game_referee1_id</code>.
     */
    public void setGameReferee1Id(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.report.game_referee1_id</code>.
     */
    public Long getGameReferee1Id() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.report.game_referee1_name</code>.
     */
    public void setGameReferee1Name(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.report.game_referee1_name</code>.
     */
    public String getGameReferee1Name() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.report.game_referee2_id</code>.
     */
    public void setGameReferee2Id(Long value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.report.game_referee2_id</code>.
     */
    public Long getGameReferee2Id() {
        return (Long) get(17);
    }

    /**
     * Setter for <code>public.report.game_referee2_name</code>.
     */
    public void setGameReferee2Name(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.report.game_referee2_name</code>.
     */
    public String getGameReferee2Name() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.report.game_referee3_id</code>.
     */
    public void setGameReferee3Id(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.report.game_referee3_id</code>.
     */
    public Long getGameReferee3Id() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>public.report.game_referee3_name</code>.
     */
    public void setGameReferee3Name(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.report.game_referee3_name</code>.
     */
    public String getGameReferee3Name() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.report.game_video_url</code>.
     */
    public void setGameVideoUrl(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.report.game_video_url</code>.
     */
    public String getGameVideoUrl() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.report.overall_score</code>.
     */
    public void setOverallScore(BigDecimal value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.report.overall_score</code>.
     */
    public BigDecimal getOverallScore() {
        return (BigDecimal) get(22);
    }

    /**
     * Setter for <code>public.report.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.report.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>public.report.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.report.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(24);
    }

    /**
     * Setter for <code>public.report.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.report.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(25);
    }

    /**
     * Setter for <code>public.report.updated_by</code>.
     */
    public void setUpdatedBy(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.report.updated_by</code>.
     */
    public Long getUpdatedBy() {
        return (Long) get(26);
    }

    /**
     * Setter for <code>public.report.finished_at</code>.
     */
    public void setFinishedAt(LocalDateTime value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.report.finished_at</code>.
     */
    public LocalDateTime getFinishedAt() {
        return (LocalDateTime) get(27);
    }

    /**
     * Setter for <code>public.report.finished_by</code>.
     */
    public void setFinishedBy(Long value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.report.finished_by</code>.
     */
    public Long getFinishedBy() {
        return (Long) get(28);
    }

    /**
     * Setter for <code>public.report.reminder_sent</code>.
     */
    public void setReminderSent(Boolean value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.report.reminder_sent</code>.
     */
    public Boolean getReminderSent() {
        return (Boolean) get(29);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportRecord
     */
    public ReportRecord() {
        super(Report.REPORT);
    }

    /**
     * Create a detached, initialised ReportRecord
     */
    public ReportRecord(Long id, String externalId, String reportType, Long coachId, String coachName, Long reporteeId, String reporteeName, String gameNumber, String gameCompetition, LocalDate gameDate, String gameResult, String gameHomeTeam, Integer gameHomeTeamId, String gameGuestTeam, Integer gameGuestTeamId, Long gameReferee1Id, String gameReferee1Name, Long gameReferee2Id, String gameReferee2Name, Long gameReferee3Id, String gameReferee3Name, String gameVideoUrl, BigDecimal overallScore, LocalDateTime createdAt, Long createdBy, LocalDateTime updatedAt, Long updatedBy, LocalDateTime finishedAt, Long finishedBy, Boolean reminderSent) {
        super(Report.REPORT);

        setId(id);
        setExternalId(externalId);
        setReportType(reportType);
        setCoachId(coachId);
        setCoachName(coachName);
        setReporteeId(reporteeId);
        setReporteeName(reporteeName);
        setGameNumber(gameNumber);
        setGameCompetition(gameCompetition);
        setGameDate(gameDate);
        setGameResult(gameResult);
        setGameHomeTeam(gameHomeTeam);
        setGameHomeTeamId(gameHomeTeamId);
        setGameGuestTeam(gameGuestTeam);
        setGameGuestTeamId(gameGuestTeamId);
        setGameReferee1Id(gameReferee1Id);
        setGameReferee1Name(gameReferee1Name);
        setGameReferee2Id(gameReferee2Id);
        setGameReferee2Name(gameReferee2Name);
        setGameReferee3Id(gameReferee3Id);
        setGameReferee3Name(gameReferee3Name);
        setGameVideoUrl(gameVideoUrl);
        setOverallScore(overallScore);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        setUpdatedAt(updatedAt);
        setUpdatedBy(updatedBy);
        setFinishedAt(finishedAt);
        setFinishedBy(finishedBy);
        setReminderSent(reminderSent);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportRecord
     */
    public ReportRecord(ch.refereecoach.probasket.jooq.tables.pojos.Report value) {
        super(Report.REPORT);

        if (value != null) {
            setId(value.getId());
            setExternalId(value.getExternalId());
            setReportType(value.getReportType());
            setCoachId(value.getCoachId());
            setCoachName(value.getCoachName());
            setReporteeId(value.getReporteeId());
            setReporteeName(value.getReporteeName());
            setGameNumber(value.getGameNumber());
            setGameCompetition(value.getGameCompetition());
            setGameDate(value.getGameDate());
            setGameResult(value.getGameResult());
            setGameHomeTeam(value.getGameHomeTeam());
            setGameHomeTeamId(value.getGameHomeTeamId());
            setGameGuestTeam(value.getGameGuestTeam());
            setGameGuestTeamId(value.getGameGuestTeamId());
            setGameReferee1Id(value.getGameReferee1Id());
            setGameReferee1Name(value.getGameReferee1Name());
            setGameReferee2Id(value.getGameReferee2Id());
            setGameReferee2Name(value.getGameReferee2Name());
            setGameReferee3Id(value.getGameReferee3Id());
            setGameReferee3Name(value.getGameReferee3Name());
            setGameVideoUrl(value.getGameVideoUrl());
            setOverallScore(value.getOverallScore());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            setUpdatedAt(value.getUpdatedAt());
            setUpdatedBy(value.getUpdatedBy());
            setFinishedAt(value.getFinishedAt());
            setFinishedBy(value.getFinishedBy());
            setReminderSent(value.getReminderSent());
            resetChangedOnNotNull();
        }
    }
}
