/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportVideoUpload;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoUploadRecord extends UpdatableRecordImpl<ReportVideoUploadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_video_upload.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_video_upload.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.report_video_upload.object_key</code>.
     */
    public void setObjectKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report_video_upload.object_key</code>.
     */
    public String getObjectKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.report_video_upload.filename</code>.
     */
    public void setFilename(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_video_upload.filename</code>.
     */
    public String getFilename() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.report_video_upload.content_type</code>.
     */
    public void setContentType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.report_video_upload.content_type</code>.
     */
    public String getContentType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.report_video_upload.size_bytes</code>.
     */
    public void setSizeBytes(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.report_video_upload.size_bytes</code>.
     */
    public Long getSizeBytes() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.report_video_upload.uploaded</code>.
     */
    public void setUploaded(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.report_video_upload.uploaded</code>.
     */
    public Boolean getUploaded() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.report_video_upload.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.report_video_upload.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.report_video_upload.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.report_video_upload.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVideoUploadRecord
     */
    public ReportVideoUploadRecord() {
        super(ReportVideoUpload.REPORT_VIDEO_UPLOAD);
    }

    /**
     * Create a detached, initialised ReportVideoUploadRecord
     */
    public ReportVideoUploadRecord(Long id, String objectKey, String filename, String contentType, Long sizeBytes, Boolean uploaded, LocalDateTime createdAt, Long createdBy) {
        super(ReportVideoUpload.REPORT_VIDEO_UPLOAD);

        setId(id);
        setObjectKey(objectKey);
        setFilename(filename);
        setContentType(contentType);
        setSizeBytes(sizeBytes);
        setUploaded(uploaded);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportVideoUploadRecord
     */
    public ReportVideoUploadRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoUpload value) {
        super(ReportVideoUpload.REPORT_VIDEO_UPLOAD);

        if (value != null) {
            setId(value.getId());
            setObjectKey(value.getObjectKey());
            setFilename(value.getFilename());
            setContentType(value.getContentType());
            setSizeBytes(value.getSizeBytes());
            setUploaded(value.getUploaded());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            resetTouchedOnNotNull();
        }
    }
}
