/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentReply;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentReplyRecord extends UpdatableRecordImpl<ReportVideoCommentReplyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_video_comment_reply.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_video_comment_reply.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>public.report_video_comment_reply.report_video_comment_id</code>.
     */
    public void setReportVideoCommentId(Long value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>public.report_video_comment_reply.report_video_comment_id</code>.
     */
    public Long getReportVideoCommentId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.report_video_comment_reply.reply</code>.
     */
    public void setReply(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_video_comment_reply.reply</code>.
     */
    public String getReply() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.report_video_comment_reply.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.report_video_comment_reply.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.report_video_comment_reply.created_by</code>.
     */
    public void setCreatedBy(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.report_video_comment_reply.created_by</code>.
     */
    public Long getCreatedBy() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVideoCommentReplyRecord
     */
    public ReportVideoCommentReplyRecord() {
        super(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY);
    }

    /**
     * Create a detached, initialised ReportVideoCommentReplyRecord
     */
    public ReportVideoCommentReplyRecord(Long id, Long reportVideoCommentId, String reply, LocalDateTime createdAt, Long createdBy) {
        super(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY);

        setId(id);
        setReportVideoCommentId(reportVideoCommentId);
        setReply(reply);
        setCreatedAt(createdAt);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportVideoCommentReplyRecord
     */
    public ReportVideoCommentReplyRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentReply value) {
        super(ReportVideoCommentReply.REPORT_VIDEO_COMMENT_REPLY);

        if (value != null) {
            setId(value.getId());
            setReportVideoCommentId(value.getReportVideoCommentId());
            setReply(value.getReply());
            setCreatedAt(value.getCreatedAt());
            setCreatedBy(value.getCreatedBy());
            resetChangedOnNotNull();
        }
    }
}
