/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportVideoCommentTag;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportVideoCommentTagRecord extends UpdatableRecordImpl<ReportVideoCommentTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>public.report_video_comment_tag.report_video_comment_id</code>.
     */
    public void setReportVideoCommentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>public.report_video_comment_tag.report_video_comment_id</code>.
     */
    public Long getReportVideoCommentId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.report_video_comment_tag.tag_id</code>.
     */
    public void setTagId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report_video_comment_tag.tag_id</code>.
     */
    public Long getTagId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportVideoCommentTagRecord
     */
    public ReportVideoCommentTagRecord() {
        super(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG);
    }

    /**
     * Create a detached, initialised ReportVideoCommentTagRecord
     */
    public ReportVideoCommentTagRecord(Long reportVideoCommentId, Long tagId) {
        super(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG);

        setReportVideoCommentId(reportVideoCommentId);
        setTagId(tagId);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportVideoCommentTagRecord
     */
    public ReportVideoCommentTagRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportVideoCommentTag value) {
        super(ReportVideoCommentTag.REPORT_VIDEO_COMMENT_TAG);

        if (value != null) {
            setReportVideoCommentId(value.getReportVideoCommentId());
            setTagId(value.getTagId());
            resetChangedOnNotNull();
        }
    }
}
