/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportComment;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportCommentRecord extends UpdatableRecordImpl<ReportCommentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_comment.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_comment.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.report_comment.report_id</code>.
     */
    public void setReportId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report_comment.report_id</code>.
     */
    public Long getReportId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.report_comment.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_comment.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.report_comment.comment</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.report_comment.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.report_comment.score</code>.
     */
    public void setScore(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.report_comment.score</code>.
     */
    public BigDecimal getScore() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportCommentRecord
     */
    public ReportCommentRecord() {
        super(ReportComment.REPORT_COMMENT);
    }

    /**
     * Create a detached, initialised ReportCommentRecord
     */
    public ReportCommentRecord(Long id, Long reportId, String type, String comment, BigDecimal score) {
        super(ReportComment.REPORT_COMMENT);

        setId(id);
        setReportId(reportId);
        setType(type);
        setComment(comment);
        setScore(score);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportCommentRecord
     */
    public ReportCommentRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportComment value) {
        super(ReportComment.REPORT_COMMENT);

        if (value != null) {
            setId(value.getId());
            setReportId(value.getReportId());
            setType(value.getType());
            setComment(value.getComment());
            setScore(value.getScore());
            resetChangedOnNotNull();
        }
    }
}
