/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportCommentsLastRead;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportCommentsLastReadRecord extends UpdatableRecordImpl<ReportCommentsLastReadRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_comments_last_read.report_id</code>.
     */
    public void setReportId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_comments_last_read.report_id</code>.
     */
    public Long getReportId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.report_comments_last_read.user_id</code>.
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report_comments_last_read.user_id</code>.
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.report_comments_last_read.last_read_at</code>.
     */
    public void setLastReadAt(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_comments_last_read.last_read_at</code>.
     */
    public LocalDateTime getLastReadAt() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportCommentsLastReadRecord
     */
    public ReportCommentsLastReadRecord() {
        super(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ);
    }

    /**
     * Create a detached, initialised ReportCommentsLastReadRecord
     */
    public ReportCommentsLastReadRecord(Long reportId, Long userId, LocalDateTime lastReadAt) {
        super(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ);

        setReportId(reportId);
        setUserId(userId);
        setLastReadAt(lastReadAt);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportCommentsLastReadRecord
     */
    public ReportCommentsLastReadRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportCommentsLastRead value) {
        super(ReportCommentsLastRead.REPORT_COMMENTS_LAST_READ);

        if (value != null) {
            setReportId(value.getReportId());
            setUserId(value.getUserId());
            setLastReadAt(value.getLastReadAt());
            resetChangedOnNotNull();
        }
    }
}
