/*
 * This file is generated by jOOQ.
 */
package ch.refereecoach.probasket.jooq.tables.records;


import ch.refereecoach.probasket.jooq.tables.ReportCriteria;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ReportCriteriaRecord extends UpdatableRecordImpl<ReportCriteriaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.report_criteria.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.report_criteria.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.report_criteria.report_id</code>.
     */
    public void setReportId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.report_criteria.report_id</code>.
     */
    public Long getReportId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.report_criteria.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.report_criteria.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.report_criteria.comment</code>.
     */
    public void setComment(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.report_criteria.comment</code>.
     */
    public String getComment() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.report_criteria.state</code>.
     */
    public void setState(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.report_criteria.state</code>.
     */
    public String getState() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ReportCriteriaRecord
     */
    public ReportCriteriaRecord() {
        super(ReportCriteria.REPORT_CRITERIA);
    }

    /**
     * Create a detached, initialised ReportCriteriaRecord
     */
    public ReportCriteriaRecord(Long id, Long reportId, String type, String comment, String state) {
        super(ReportCriteria.REPORT_CRITERIA);

        setId(id);
        setReportId(reportId);
        setType(type);
        setComment(comment);
        setState(state);
        resetChangedOnNotNull();
    }

    /**
     * Create a detached, initialised ReportCriteriaRecord
     */
    public ReportCriteriaRecord(ch.refereecoach.probasket.jooq.tables.pojos.ReportCriteria value) {
        super(ReportCriteria.REPORT_CRITERIA);

        if (value != null) {
            setId(value.getId());
            setReportId(value.getReportId());
            setType(value.getType());
            setComment(value.getComment());
            setState(value.getState());
            resetChangedOnNotNull();
        }
    }
}
